### PR TITLE
Increment versions of k8s used in CI

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Instead of 1.21 and 1.22, now use 1.22 and 1.23

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
Won't we have to switch to 1.24 just in a bit?

**Comment by awels** [comment]
Well not sure when 1.24 becomes available in kubevirtci, also we can decide if that is something we want to do or not at any time.

**Comment by akalenyu** [comment]
> Well not sure when 1.24 becomes available in kubevirtci, also we can decide if that is something we want to do or not at any time.

Gotcha, right
BTW on k8s > 1.22 rook will fail to deploy the CSIDriver object and this possibly explains the failures, more detail in:
https://github.com/kubevirt/kubevirtci/pull/794

And an attempt to handle some related nils on looking up csidrivers:
https://github.com/kubevirt/containerized-data-importer/pull/2253

**Comment by awels** [comment]
Yeah there seems to be a problem with https://github.com/kubevirt/kubevirtci/pull/794 with some of the tests.

**Comment by akalenyu** [comment]
@awels ceph bump merged in kubevirtci, would you like to bump it here or new PR?

**Comment by awels** [comment]
I was waiting for that to merge, going to bump it here

**Comment by akalenyu** [comment]
/test pull-containerized-data-importer-e2e-hpp-latest
https://github.com/kubevirt/containerized-data-importer/issues/1988

**Comment by akalenyu** [comment]
Same exact amount of ceph tests as before
/lgtm

**Comment by akalenyu** [comment]
@awels should we cherry pick to 49?

**Comment by awels** [comment]
Yeah since we want 1.49 to support k8s 1.23 at a minimum.
/cherrypick release-v1.49

**Pull request merged**
