### PR TITLE
Less dependencies for containerized-data-importer-api

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Generate golang openapi spec files in `pkg/apis` instead of `staging/src/kubevirt.io/containerized-data-importer-api/`. This allows reducing some dependencies for third parties using our api repos.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove kube-openapi dependencies from the published api definition
```

### CODE REVIEW

**Comment by rmohr** [comment]
@nirarg could you check if that is sufficient or do we have to get rid of kubevirt.io/controller-lifecycle-operator-sdk right now already?

**Comment by mhenriks** [comment]
Thanks @rmohr!

**Pull request merged**
