### PR TITLE
Have the csv generator generate the dataimportcron CRD as well

### PR DESCRIPTION
**Pull request by maya-r**
```release-note
Have the cdi-operator csv generator generate the dataimportcron CRD as well
```

### CODE REVIEW

**Comment by arnongilboa** [comment]
@maya-r please `gofmt -w tools/csv-generator/csv-generator.go` to get  linter happier

**Comment by maya-r** [comment]
@akalenyu was wondering why this isn't necessary for the datasource crd, and I'm not sure why that is the case.
@nunnatsa is this because SSP is using this CRD and so we can't wait for the cdi-operator to create the CRD?

**Comment by mhenriks** [comment]
DataSource should probably be included as well

**Comment by mhenriks** [comment]
Actually, why is this needed?

**Comment by mhenriks** [comment]
The cdi operator is creating/managing this CRD (in addition to others)

**Comment by nunnatsa** [comment]
> The cdi operator is creating/managing this CRD (in addition to others)

@mhenriks - when installing using OLM, the SSP is trying to read DataImportCrons and failed because of the missing CRD. It then get into crash loop, so OLM can never complete the installation of the csv. Only after creating tje HyperConvered CR, HCO creates the CDI CR and only then, the CRD is created by CDI.

**Comment by mhenriks** [comment]
>. @mhenriks - when installing using OLM, the SSP is trying to read DataImportCrons and failed because of the missing CRD. It then get into crash loop, so OLM can never complete the installation of the csv. Only after creating tje HyperConvered CR, HCO creates the CDI CR and only then, the CRD is created by CDI.

SSP should not be that tightly coupled to CDI, handle the DataImportCron not existing, and discover when they do exist.  CDI does this for multiple resources.  VolumeSnapshots, for example.

**Comment by awels** [comment]
I agree with @mhenriks the CDI operator is the one creating and managing the CRDs, it does this perfectly fine with many other CRDs, including datavolumes. I don't see why DIC is any different.

**Comment by maya-r** [comment]
Closing as I agree with the responses - SSP should be more tolerant of this scenario.

**Comment by nunnatsa** [comment]
@maya-r @mhenriks @awels @arnongilboa - please reconsider this.

Regardless the behavior SSP, what is the benefit to dynamically add/remove the CRD? It causes issues in the installation, and then again during uninstall. It would be much simpler if the CDR will be a static file in the installation.

**Pull request closed without merging**
