### PR TITLE
Revert LVMO storage CSI snapshot clone.

### PR DESCRIPTION
**Pull request by awels**
**What this PR does / why we need it**:
On multi node LMVO this setting can cause issues so reverting to host assisted clone which works everywhere
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/hold
could you please also revert golden snapshot sources? otherwise, it'll attempt restores from snapshot
https://github.com/kubevirt/containerized-data-importer/pull/3196/files#diff-a21d708ef3a53b6344a19726606fc760e43ce13f1927330084763c6f584196f2R114-R115

**Comment by awels** [comment]
Done, completely missed that.

**Comment by akalenyu** [comment]
> Done, completely missed that.

Me too..

**Pull request merged**
