### PR TITLE
VDDK: more reliable transfers of full disks.

### LINKED ISSUE #1544: VDDK: importer crash on cold migration
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Copying from a VDDK data source crashed on an unhelpfully large pwrite.

**What you expected to happen**:
A good copy without a crash.

**How to reproduce it (as minimally and precisely as possible)**:
Regular VDDK import with a source disk that is very full.

**Anything else we need to know?**:
I have a fix incoming.

### PR DESCRIPTION
**Pull request by mrnold**
**What this PR does / why we need it**:
Fixes a VDDK importer crash, and reports progress correctly.

**Which issue(s) this PR fixes** :
Fixes #1544 

**Special notes for your reviewer**:
Tested a wider range of source disk images this time - originally I tested with disks that had lots of zero blocks, so I did not see this bug.

**Release note**:

```release-note
Fixed an importer crash when copying from a VDDK data source.
```

### CODE REVIEW

**Comment by maya-r** [comment]
Can you add a release note?

**Comment by mrnold** [comment]
Thank you!

**Pull request merged**
