### PR TITLE
Add fossa check for licenses.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Add the infra structure needed to run fossa on CDI, once we have sanitized CDI, we can update KubeVirt so it won't fail either.

Once https://github.com/kubevirt/project-infra/pull/2251 is merged we can attempt to run the lane

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by dhiller — COMMENTED** [review]
In the presubmit you are [using the `make fossa` target](https://github.com/kubevirt/project-infra/pull/2251/files#diff-0598ff03c5cec02cf9dd01b94ea8f4ba29795085541ddefa627d65f7cf926dcbR416), which I don't see here. Am I missing something here?

**Comment by awels** [comment]
No I forgot to add it, I am in the middle of an update to this PR to add that target.

**Review by akalenyu — COMMENTED** [review]
Dug out this comment:
https://github.com/kubevirt/kubevirt/issues/7573#issuecomment-1099190471
Wonder what is the procedure to `mark the fossa alerts as "false alerts"`

**Comment by awels** [comment]
There is an option in the fossa UI to mark flagged warnings as false positives.

**Comment by awels** [comment]
Supposedly we have no more warnings at this point. lets find out

**Comment by brybacki** [comment]
on test failed:  `Tests Suite: DataImportCron should [test_id:8266] succeed deleting error DVs when importing new ones` maybe it is a flaky one?
/test pull-containerized-data-importer-e2e-istio

**Comment by maya-r** [comment]
I've modified the fossa lane regex to not run on release lanes (it looked like an accident that it did), so cherry-picking to release-v1.49 might not be necessary

**Pull request merged**
