### PR TITLE
Fix types.go vs code schema verification to actually fail if they are different

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
We checked that the schema matched, however the code that was supposed to generate a failure didn't so even though we checked inconsistencies managed to get in. This PR ensures the job fails so we can't get inconsistent code into the code base.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Nice, it looks like the reason I have two separate tests for invalid filesystem overhead values is gone

**Comment by maya-r** [comment]
Do you want to mark those as expected fail and I'll fix this in a separate PR?

**Comment by awels** [comment]
Hmmm when I run these locally they all pass....

**Comment by awels** [comment]
Well the thing is the failures are valid, and we should allow blank overhead in the cases that are failing right now. Since it should just pick the global overhead in that case. But they pass for me locally.....

**Comment by maya-r** [comment]
I had assumed that pattern validation doesn't work for the per-storageclass case and checked whether the status gets changed. Your change adds regex validation so the update is rejected

**Comment by awels** [comment]
Now I know why it was passing locally, I was looking at the wrong tests. I fixed the tests.

**Comment by awels** [comment]
@maya-r I fixed the tests, and they are all passing now.

**Pull request merged**
