### PR TITLE
Fix Secret URL

### PR DESCRIPTION
**Pull request by jeesmon**
Signed-off-by: Jeesmon Jacob <jjacob@us.ibm.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Fix URL in the doc

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jeesmon** [comment]
@awels Should I worry about the above failed tests? Thanks

**Comment by awels** [comment]
no we have some flaky tests.

**Pull request merged**
