### PR TITLE
Upgrade test - debug

### PR DESCRIPTION
**Pull request by arnongilboa**
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
IIRC the skips/focuses in the ginkgo binary call will mess up your test focus, this is how I did it last time:
https://github.com/kubevirt/containerized-data-importer/pull/2384#issuecomment-1221530601

**Comment by brybacki** [comment]
and locally this is much easier if you have TEST_ID:
`make TEST_ARGS="--test-args=-ginkgo.focus=<TEST_ID> -ginkgo.regexScansFilePath=false" test-functional`

**Comment by arnongilboa** [comment]
> and locally this is much easier if you have TEST_ID: `make TEST_ARGS="--test-args=-ginkgo.focus=<TEST_ID> -ginkgo.regexScansFilePath=false" test-functional`

Sure, I did it many times, but had no luck running the mentioned upgrade test locally....

**Comment by brybacki** [comment]
@arnongilboa did you find a problem?

**Pull request closed without merging**
