### PR TITLE
modify default k8s version in cluster-up

### PR DESCRIPTION
**Pull request by anencore94**
**What this PR does / why we need it**:

Following the docs ('Getting started for developers' in ./hack/README.md), it says 'cluster-up' command use KUBEVIRT_PROVIDER value as default k8s-1.16.2.

However, it uses k8s-1.13.3 actually. Thus the command fails.

Thus, i modify it to set k8s-1.16.2 by default, which is the value written in developers guide.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
@anencore94 please sign off on commits

**Comment by maya-r** [comment]
the signed off line appears, but the bot is not picking it up for some reason (possibly a whitespace issue?)

**Comment by anencore94** [comment]
> the signed off line appears, but the bot is not picking it up for some reason (possibly a whitespace issue?)

Thanks. I don't know why the bot didn't pick, but it was because of the whitespace as you mentioned.

**Pull request merged**
