### PR TITLE
Controller support for Multistage Imports

### PR DESCRIPTION
**Pull request by mansam**
**What this PR does / why we need it**:

This PR adds controller support that is needed for multistage imports.

* Add Previous, Current, and FinalCheckpoint to DataVolume CRD
* Use checkpoints from the DV to set annotations on the PVC
* If an importer pod succeeds while checkpoint annotations are set,
  then set the DataVolume status to Paused instead of Succeeded.
* Sets the Importer pod environment variables from the checkpoint annotations
* Clear the PVC checkpoint annotations when a stage completes

Fixes https://github.com/kubevirt/containerized-data-importer/issues/1407

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
if you rebase most of the flaky failures should go away.

**Comment by awels** [comment]
Also, I am missing something here, I see the new fields and annotations, however I don't really see code using them. Is that a follow up PR?

**Comment by mansam** [comment]
@awels Yes, this will require a follow up PR to enable the importer pod to make use of these annotations to perform warm imports.

**Comment by mansam** [comment]
Rebased on master.

**Pull request merged**
