### PR TITLE
Ignore error in upload copy test

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Ignore the error, it might be because the other end closed the connection because it was done. We verify the image uploaded
by md5 anyway.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
So I suppose that we do not care what kind of error that is (like connection closed or something like that), because it is just a test , and as your comment states everything is verified at the end?

/lgtm

**Comment by awels** [comment]
The idea is that io.Copy can still copy bytes even if there is an error. Like one side closing the connection because it is done sending or receiving. And that error is harmless.

**Comment by awels** [comment]
Seems like maybe I haven't completely solved the terminating scratch space issue with warm imports.

**Pull request merged**
