### PR TITLE
Update cdi-testing-sa SCC to work in newer Open Shift

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
The SCC was not applying properly due to some missing required fields. This PR adds those fields.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by akalenyu — COMMENTED** [review]
Which openshift are you on?
I observed this being applied totally fine on latest

**Comment by awels** [comment]
I am running hypershift 4.11.7 and it rejected that SCC until I added the required fields. If you look at the documentation https://docs.openshift.com/container-platform/4.11/rest_api/security_apis/securitycontextconstraints-security-openshift-io-v1.html you will see these are required fields.

**Pull request merged**
