### PR TITLE
Flaky cert test fix

### LINKED ISSUE #1596: [flaky CI] ALL Operator tests Operator cert config tests should allow update
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:
Several test runs failed with: ALL Operator tests Operator cert config tests should allow update
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1565/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1351624394878750720
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1565/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1350081798712856576
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

More robust retry handling because we may have read date between updates (one annotation updated and not the other)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1596 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by awels — COMMENTED** [review]
/lgtm
/approve

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.18-upg
(35 failures. possibly a cluster issue.)

**Pull request merged**
