### PR TITLE
Separate sdk api

### LINKED ISSUE #2029: Further reduce api dependencies
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

Using `kubevirt.io/api` and `kubevirt.io/containerized-data-importer-api` really trimms down dependencies for third party integrators.

There are still a few dependencies which would be great if we could get rid of:

For instance `emicklei/go-restful` and `kube-openapi`:

```
$ bazel query "allpaths(//staging/src/kubevirt.io/api/..., //vendor/github.com/emicklei/go-restful:go_default_library)"
//staging/src/kubevirt.io/api/snapshot/v1alpha1:go_default_library
//staging/src/kubevirt.io/api/flavor/v1alpha1:go_default_library
//staging/src/kubevirt.io/api/core/v1:go_default_library
//vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1:go_default_library
//vendor/k8s.io/kube-openapi/pkg/common:go_default_library
//vendor/github.com/emicklei/go-restful:go_default_library
```

Also `kubevirt.io/controller-lifecycle-operator-sdk` may be a potential issue.

**What you expected to happen**:

That we don't pull in e.g. `go-openapi` if a project does not need it on its own. Happens for instance here: https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/pull/17/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by rmohr**
**What this PR does / why we need it**:

Remove api dependencies by using a separate api package from the sdk: https://github.com/kubevirt/controller-lifecycle-operator-sdk/pull/22

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2029 

**Special notes for your reviewer**:

**Release note**:

```release-note
Reduce cdi api dependencies by using a separated controller-runtime-sdk api package
```

### CODE REVIEW

**Comment by rmohr** [comment]
/hold

needs https://github.com/kubevirt/controller-lifecycle-operator-sdk/pull/22 merged.

**Comment by brybacki** [comment]
This is nice change.

I think the first PR commit could say (in case someone whats to find it in the future):
`Introduce controller-runtime-sdk api package` 

I have skipped the `go mod` commit and looking into the code references now. But as tests are passing I suppose it is all good.

**Comment by rmohr** [comment]
> I think the first PR commit could say (in case someone whats to find it in the future):
> `Introduce controller-runtime-sdk api package`

Done

**Comment by brybacki** [comment]
/retest
imageio tests are under investigation, we might want to skip them

**Pull request merged**
