### PR TITLE
Add validation of content type and unit tests.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Adds validation of content type in data volumes.
Adds unit tests to verify the validation.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Added validation of content type in data volumes.
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
Well some of the point of this exercise is to actually apply manifests to a cluster and see what happens. Instead of programatically generating the manifest (which is not what a human would do). We have the unit tests that handle that aspect of the testing.

**Comment by mhenriks** [comment]
@awels I was not suggesting that we generate manifests from code.  There are a ton of places in the functional tests where resources are created by client-go.  This is the only test that uses manifests and kubectl.  Was wondering why this test special.

**Comment by awels** [comment]
Because for this particular test, we explicitly wanted manually created manifests that are called by kubectl. To test what actual humans would do instead of some go client. To catch things like the status field missing causing errors instead of what the client generated (it might have seen the required on that field, and generated an empty field instead of bombing like a manual manifest would have done)

**Pull request merged**
