### PR TITLE
doc: Add storage class to example PVC

### LINKED ISSUE #221: add storageclass to golden-pvc example
I think it will be good to add the storageclass (marked as optional) to the example file
manifests/example/golden-pvc.yaml

it would be extra nice to have at least some of the available values there as well,
i keep forgetting how to mark glusterfs :)

### PR DESCRIPTION
**Pull request by aglitke**
Fixes #221.

Signed-off-by: Adam Litke <alitke@redhat.com>

### CODE REVIEW

**Comment by j-griffith** [comment]
ci test please

**Comment by j-griffith** [comment]
Hmm... that doesn't re-kick Travis?

**Comment by awels** [comment]
No just STD-CI, I think the problem is that one of the tests actually use that yaml file, which now has a storage class that doesn't exist.

**Comment by aglitke** [comment]
Interesting.  When I do a make cluster-up I get a storage class called 'local'

**Comment by awels** [comment]
Right that is the 'local volume' storage class. But none of that exists in travis ci.

**Pull request merged**
