### PR TITLE
Global preallocation setting is not taken into account correctly.

### PR DESCRIPTION
**Pull request by tomob**
Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1915704

Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by awels — CHANGES_REQUESTED** [review]
So this does not actually fix the problem. We should be getting the status.Preallocation, which is calculated from spec.Preallocation in the CDIConfig controller. So the fix would be to properly calculate the value in the controller, and update the CDIConfig object there. Especially since the spec.preallocation is optional, if it is not specified in the spec, the status should return false. If you reference the spec directly you could get nil pointers.

**Comment by awels** [comment]
You can do something like in the main config-controller reconcile loop:
```go
// Keep a copy of the original for comparison later.
currentConfigCopy := config.DeepCopyObject()

config.Status.Preallocation = config.Spec.Preallocation != nil && config.Spec.Preallocation
```
As well as making config.Spec.Preallocation a *bool for the reasons Michael pointed out (its omitempty) That basically sets the Status to false if Spec is nil or false, and true if Spec is not nil and true

**Comment by tomob** [comment]
When is #1556 intended to be merged? The change in config loop would depend on that.

**Comment by awels** [comment]
I asked Michael to take the change out of #1556 that is unrelated to the docs. So if you could change it in this PR.

**Comment by mhenriks** [comment]
@tomob I reverted the change in #1556 so you can make it here

**Comment by tomob** [comment]
> @tomob I reverted the change in #1556 so you can make it here

Thanks!

**Comment by awels** [comment]
Don't forget to run make generate after making the change in the struct.

**Review by awels — APPROVED** [review]

**Pull request merged**
