### PR TITLE
Remove tag from DataImportCron registry source URL

### PR DESCRIPTION
**Pull request by arnongilboa**
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>

**What this PR does / why we need it**:
There are cases when DataImportCron registry source URL contains tag referring a specific version. We use this tagged URL when polling for source updates, but on import we would like to remove the tag as we use a specific sha256.
E.g. for `docker://quay.io/containerdisks/centos:8.4` the `:8.4` tag will be removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by dominikholler — APPROVED** [review]
/lgtm
@arnongilboa Thanks a lot for introducing this improvement!

**Comment by dominikholler** [comment]
/lgtm
@arnongilboa thanks for the improvement

**Comment by awels** [comment]
I was looking at maybe looking some existing library functions to strip the tag.

**Comment by arnongilboa** [comment]
> I was looking at maybe looking some existing library functions to strip the tag.

Sure looked for it, but unfortunately couldn't find. Will be happy to find one.

**Comment by awels** [comment]
So using the [docker reference](https://github.com/kubevirt/containerized-data-importer/tree/main/vendor/github.com/containers/image/v5/docker/reference) code you can parse the URL and it should return you a reference. If the URL contains a tag it should be a `NamedTagged` or `Tagged` reference. Doing a check for either might be a little overkill, but I would at least use the Regex found [here](https://github.com/kubevirt/containerized-data-importer/blob/main/vendor/github.com/containers/image/v5/docker/reference/regexp.go#L68) to capture the right things in a consistent fashion.

**Pull request merged**
