### PR TITLE
rm tests/manifests/out and add to .gitignore

### PR DESCRIPTION
**Pull request by arnongilboa**
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>

**What this PR does / why we need it**:
Out files are generated during functional test run and should not be git'ed.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Maybe this needs to be in .gitignore

**Comment by mhenriks** [comment]
yes @maya-r good call pleas add to .gitignore so some bonehead like me doesn't do this again

**Comment by arnongilboa** [comment]
@maya-r @mhenriks added to .gitignore

**Pull request merged**
