### PR TITLE
Skip code-block formatting from api-reference

### PR DESCRIPTION
**Pull request by alromeros**
**What this PR does / why we need it**:

Our api-reference broke due to `quantity`'s description containing code-block formatting that's not rendered properly: https://kubevirt.io/cdi-api-reference/main/definitions.html.

Kubevirt [skips code-block formatting ](https://github.com/kubevirt/kubevirt/blob/main/hack/gen-swagger-doc/gen-swagger-docs.sh#L72)to avoid this behavior, so we should do the same.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubevirt/containerized-data-importer/issues/2827

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by aglitke — APPROVED** [review]
/lgtm

**Comment by awels** [comment]
the failure looks like a race condition on when the `source-pod` is deleted. Which it should not be doing since we annotated the DV with the `retainAfterCompletion` annotation. So there might be a bug in that for the source pod.

**Comment by alromeros** [comment]
> the failure looks like a race condition on when the `source-pod` is deleted. Which it should not be doing since we annotated the DV with the `retainAfterCompletion` annotation. So there might be a bug in that for the source pod.
> 
> More investigation, the target PVC has the annotation, but I see no evidence of the source pod ever getting created. The clone is not complete. The source pod name was generated, and visible on the target PVC, but no logs or events about that name at all.
> 
> Failure happened in the legacy hpp lane, no CSI and no populators.

I don't remember which test failed, do you know if the error can be replicated consistently? Any other PRs where it happened?

**Comment by awels** [comment]
https://github.com/kubevirt/containerized-data-importer/blob/main/tests/datavolume_test.go#L1687-L1744 is the test that failed, in particular it failed on line 1743 in that it could not find the source pod to read some information from.

**Pull request merged**
