### PR TITLE
rename importController to uploadController in the upload-controller.go file

### PR DESCRIPTION
**Pull request by threestoneliu**
**What this PR does / why we need it**:
rename importController to uploadController in the upload-controller.go file

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by awels — COMMENTED** [review]
/lgtm
/ok-to-test
/approve

**Comment by awels** [comment]
Thanks for the fixes.

**Comment by threestoneliu** [comment]
@awels ，please review again，and add lgtm label. Some e2e test failed, but i use force push instead of say `/retest` to trigger the github action. And forgive my stupid operation.

**Comment by awels** [comment]
Don't worry about the failures. We have some flakey tests that we are working on fixing, but in the meantime they will produce some noise.

**Pull request merged**
