### PR TITLE
Enable autoformatting linters

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**What this PR does / why we need it**:
This PR adds a few linters that autoformat the code. This should help make the codebase more consistent in style, as is the Go way. 
- `Gofmt` checks whether code was gofmt-ed. By default this tool runs with -s option to check for code simplification.
- `Whitespace` is a linter that checks for unnecessary newlines at the start and end of functions, if, for, etc.
- `Gci` controls Go package import order and makes it always deterministic. This one produces a big diff though.

**How to run them**
In CI runs, these will not autoformat and instead will just complain. Locally, you can run them with:
```
golangci-lint run ./... --fix
```

If you're using VSCode, you can add these options so the it runs when you save. I'm sure other editors have similar options.
```jsonc
"go.lintOnSave": "file", // Optional, makes it faster
"go.lintTool": "golangci-lint",
"go.lintFlags": [ "--fix" ],
```

**Special notes for your reviewer**:
The only manual changes are ones made to `.golangci.yaml`. Everythin else is auto-formatted.
I recommend reviewing this PR commit by commit as the result is very large.

**Release note**:

```release-note
Enable autoformatting linters and format the project
```

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
If the amount of changes is too scary, I can get rid of the GCI linter as that's where the majority of them come from.

**Comment by alromeros** [comment]
Thanks for the PR! This improves consistency and looks good to me, let's see what others think.

**Comment by mhenriks** [comment]
>Locally, you can run them with:
 golangci-lint run ./... --fix

Can we add a make target that runs this in the builder container?

**Comment by EduardGomezEscandell** [comment]
> Can we add a make target that runs this in the builder container?

Already on it #3193 :smiley: 

The idea is to add this to `make format`.

**Pull request merged**
