### PR TITLE
Remove invalid-qcow-large-size.img tests.

### PR DESCRIPTION
**Pull request by maya-r**
This image is malformed, and depending on the qemu-img version used,
it might not be recognized as a qcow2 and handled as a RAW file.
This caused us some pain in the past.

The use case of importing a too large image is already covered by
test_id:2329.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by arnongilboa** [comment]
/lgtm
but can you expand a bit on the different qemu-img versions behavior?

**Comment by maya-r** [comment]
With fedora (similar to upstream):
```
$ qemu-img --version; qemu-img info invalid-qcow-large-size.img 
qemu-img version 5.1.0 (qemu-5.1.0-9.fc33)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
image: invalid-qcow-large-size.img
file format: qcow
virtual size: 152 TiB (167125767422464 bytes)
disk size: 4 KiB
cluster_size: 4096
```

With downstream's qemu-img:
```
$ ./usr/bin/qemu-img --version; ./usr/bin/qemu-img info invalid-qcow-large-size.img 
qemu-img version 5.1.0 (qemu-kvm-5.1.0-14.module+el8.3.0+8790+80f9c6d8.1)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
image: invalid-qcow-large-size.img
file format: raw
virtual size: 1 KiB (1024 bytes)
disk size: 4 KiB
```

**Pull request merged**
