### PR TITLE
Add test cases for runbook URLs

### PR DESCRIPTION
**Pull request by assafad**
This PR adds new tests cases for alert definitions. We expect to see "runbook_url" annotations in alerts and those urls must be accessible.

Signed-off-by: assafad <aadmi@redhat.com>

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by assafad** [comment]
Hi @erkanerol , @sradco , @akalenyu , can you please review this PR?

**Comment by akalenyu** [comment]
/ok-to-test

We have a case that grabs the prometheusrule:
https://github.com/kubevirt/containerized-data-importer/blob/10c85dc73a11e1ec97defdc7a68923d05af6f010/pkg/operator/controller/controller_test.go#L331
If you want to use that 

Otherwise, a little unsure on unit tests making real HTTP call. how horrible is that? does it justify a functest?
(this is just to make sure the runbook page exists i.e. there is a runbook for the alert)

**Pull request merged**
