### PR TITLE
Remove openshift dep on api

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Less deps the better!  Could be problematic for projects importing CDI and openshift.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Copied file over from openshift

**Release note**:

```release-note
Remove API dependency on openshift/api
```

### CODE REVIEW

**Comment by mhenriks** [comment]
cc @akalenyu

**Review by akalenyu — COMMENTED** [review]
/approve

**Comment by akalenyu** [comment]
/test pull-cdi-unit-test
```
  [FAILED] Expected
      <time.Time>: 2024-04-10T16:52:06Z
  to be <
      <time.Time>: 2024-04-10T14:52:05Z
```
WHAT?

**Comment by nunnatsa** [comment]
>  Could be problematic for projects importing CDI and openshift

yap! https://github.com/kubevirt/hyperconverged-cluster-operator/pull/3059

**Pull request merged**
