### PR TITLE
[release-v1.49] backport tar handling from #2410

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

May be helpful to backport new tar behavior to avaoid EPERM

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

https://bugzilla.redhat.com/show_bug.cgi?id=2184386

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
> Back in 1.49, we are still running as root, so that err is a bit surprising no?
> 
> https://github.com/kubevirt/containerized-data-importer/blob/c8f96f9585aa36902f49cfb554336fafdd86fcc6/pkg/controller/clone-controller.go#L592
> 
> But this does remind me of an nfs root squash misconfiguration which we recently heard about, will try to find that discussion

Yeah, that may be it but there is a detailed trace in the bz.  this change should keep that error from occurring.  not sure if some other error will pop up though

**Comment by akalenyu** [comment]
> > Back in 1.49, we are still running as root, so that err is a bit surprising no?
> > https://github.com/kubevirt/containerized-data-importer/blob/c8f96f9585aa36902f49cfb554336fafdd86fcc6/pkg/controller/clone-controller.go#L592
> > 
> > But this does remind me of an nfs root squash misconfiguration which we recently heard about, will try to find that discussion
> 
> Yeah, that may be it but there is a detailed trace in the bz. this change should keep that error from occurring. not sure if some other error will pop up though

gotcha yeah it should not happen, was just wondering how we hit it in the first place,
being root. I guess when the squash is messed up it just doesn't matter that you're running as root in the container.

/lgtm
/test pull-cdi-generate-verify-1.49

**Comment by akalenyu** [comment]
Apparently the generate error has been around for a while
(failed in https://github.com/kubevirt/containerized-data-importer/pull/2659)
@awels @brianmcarey Any idea what can cause this on the 1.49 lanes?

**Pull request merged**
