### PR TITLE
Test behavior after client-side upload failure.

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:

Add the automated test causing a client side upload failure during upload. After verifying failure, the test continues with correct upload to check if the DV upload is eventually consistent and can finish successfully.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
I just realized I can add a check for some condition or maybe an event after the first failure - before continuing with "good" upload

**Comment by brybacki** [comment]
Actually I cannot see any obvious events/conditions created when the client experiences failure. The upload server just waits for oncoming data, and when good data is received - operation succeeds.

**Review by awels — APPROVED** [review]
/lgtm

**Review by kgoldbla — COMMENTED** [review]
LGTM

**Pull request merged**
