### PR TITLE
update k8s image to 1.13.3 and enable ceph

### PR DESCRIPTION
**Pull request by igoihman**
Signed-off-by: Irit goihman <igoihman@redhat.com>

**What this PR does / why we need it**:
Changed k8s version to 1.13.3, updated gocli image and enabled Ceph.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by j-griffith** [comment]
This is great, one quick question; just to verify.  Is there any value in keeping the storage option selectable?  So like by default we go with the ceph work you added to the CI but still allow a variable to override or fall back to local storage if we need to?  We can always do it as follow up work but wanted to throw it out there.  I'm happy to see this merge as is.

**Comment by igoihman** [comment]
@j-griffith This change just changes the image and now we will have static provisiong with local volume and dynamic provisioning using Ceph CSI provisioner.
In order to actually start using Ceph in our tests we need to indicate its storage class (I think local storage class is still the default).
But, we need to pay attention to QE, they are running our functional tests in their system with different storage classes and we should avoid making assumptions of the storage class names - Maybe just test on all available storage classes?

**Comment by igoihman** [comment]
ci test please

**Comment by rollandf** [comment]
:+1:

**Comment by awels** [comment]
> @j-griffith This PR just changes the image and now we will haveboth static provisioning with local storage and dynamic provisioning using Ceph CSI provisioner.
> In order to actually start using Ceph in our tests we need to indicate its storage class (I think local storage class is still the default).
> But, we need to pay attention to QE, they are running our functional tests in their system with different storage classes and we should avoid making assumptions of the storage class names - Maybe just test all available storage classes?

Maybe add a tests_args parameter that specifies the ceph/dynamic/block storage class name, so QE can override it with whatever they have set up? Which then ends up as a flag in the test suite, and our tests can simply reference that flag for the storage class name for tests that require that kind of storage.

**Comment by igoihman** [comment]
@awels sounds like a good idea

**Pull request merged**
