### PR TITLE
Update kubevirtci

### LINKED ISSUE #1575: CI occasionally fails with "binding device to vfio driver failed"
/kind bug
/triage build-watcher

**What happened**:
The following run is an example of a failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1571/pull-containerized-data-importer-e2e-k8s-1.18-hpp/1351090250511814656

**What you expected to happen**:
Non-flaky CI.

### PR DESCRIPTION
**Pull request by maya-r**
kubevirtci already contains a fix for the VFIO failures we see from time to time, let's pick up the fix.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1575 (apparently).

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
having the vfio failure in this PR is not promising :)
/test pull-containerized-data-importer-e2e-k8s-1.18-nfs

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.18-upg
--

**Comment by awels** [comment]
If you want to test the lanes, you need to update cluster-sync to also know what to do the new providers.

**Pull request merged**
