### PR TITLE
Read-only mounts in clone source pods

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Read/write mounts will minimize errors when a source PVC is mounted multiple times on the same node.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

This is two part of a two PR fix for https://bugzilla.redhat.com/show_bug.cgi?id=1893363

Once this and #521 are merged I will add a new functional test to stress cloning hard

**Special notes for your reviewer**:

**Release note**:

```release-note
Clone source pods mount PVCs read-only
```

### CODE REVIEW

**Comment by maya-r** [comment]
Can you elaborate in the commit message and/or split it into: read-only pod, then removing the clone source filtering (not currently explained in the commit message)?

looks good to me otherwise.

**Comment by maya-r** [comment]
I'm not very knowledgeable about selinux. is this too much permissions to grant to a pod? the internet seems to imply it's giving a lot of access to the host.

**Comment by mhenriks** [comment]
> I'm not very knowledgeable about selinux. is this too much permissions to grant to a pod? the internet seems to imply it's giving a lot of access to the host.

Clone source pods don't mount any path on the host, though.  Well, not including the PVC of course.  And that is mounted read only.

**Comment by awels** [comment]
That is the same selinux context as KubeVirt gives the virt-launcher pods.

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
