### PR TITLE
[WIP] Set importer restart policy to never to avoid race condition during termination

### PR DESCRIPTION
**Pull request by alromeros**
**What this PR does / why we need it**:

This is an alternative to https://github.com/kubevirt/containerized-data-importer/pull/3044.

This pull request changes the importer restart policy from "on failure" to "never". The old behavior caused some issues during termination while the pod was already restarting after scratchSpaceNeeded.

Importer pod lifecycle for a regular DV before the fix:

```sh
# k get pod importer-cirros-dv-source -woyaml | grep exitCode
selecting docker as container runtime
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 2
        exitCode: 42
        exitCode: 2
        exitCode: 42
        exitCode: 2
        exitCode: 0
        exitCode: 0
```

After the fix:

```sh
# k get pod importer-cirros-dv-source -woyaml | grep exitCode
selecting docker as container runtime
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 42
        exitCode: 0
        exitCode: 0
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2240963 (follow-up)

**Special notes for your reviewer**:

Let's see how tests behave and decide which option is better.

**Release note**:

```release-note
Bugfix: Avoid race condition during importer termination
```

### CODE REVIEW

**Comment by alromeros** [comment]
/hold

Let's see how well tests behave and decide whether https://github.com/kubevirt/containerized-data-importer/pull/3044 or this is a better option.

**Comment by akalenyu** [comment]
> /hold
> 
> Let's see how well tests behave and decide whether #3044 or this is a better option.

I honestly don't know about this approach.. consider intermittent `err != nil`s in the importer execution, like, HTTP flukes for example. We do want to be eventually consistent and keep trying on those

**Comment by alromeros** [comment]
> > /hold
> > Let's see how well tests behave and decide whether #3044 or this is a better option.
> 
> I honestly don't know about this approach.. consider intermittent `err != nil`s in the importer execution, like, HTTP flukes for example. We do want to be eventually consistent and keep trying on those

I kinda agree, I want to have some discussion around this but even if we manually restart the importer, this method seems more buggy and prone to breaking than setting the 0 grace period.

**Comment by alromeros** [comment]
I think I found a better alternative that's less intrusive to our tests. Closing this and opening a new PR.

**Pull request closed without merging**
