### PR TITLE
[release-1.43] Queue DataVolumes referred to in "populatedFor" PVC annotations

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

https://bugzilla.redhat.com/show_bug.cgi?id=2149671

**Special notes for your reviewer**:

Manual backport of https://github.com/kubevirt/containerized-data-importer/pull/2373

**Release note**:

```release-note
Fix DataVolume/PVC restore - don't require PVC initially owned by DataVolume
```

### CODE REVIEW

**Comment by awels** [comment]
Hmm so we should not have DV GC enabled here...

**Comment by mhenriks** [comment]
> Hmm so we should not have DV GC enabled here...

Yes that is how these backport PRs differ from the original.  Do you see an issue?

**Comment by awels** [comment]
So I am guessing that this lane is failing due to us not backporting the fix into this branch and stuff getting garbage collected, and the DVs disappearing. We can override the lane or backport the fix.

**Comment by mhenriks** [comment]
> So I am guessing that this lane is failing due to us not backporting the fix into this branch and stuff getting garbage collected, and the DVs disappearing. We can override the lane or backport the fix.

What fix are you talking about?

**Comment by awels** [comment]
So the problem is that we are installing the 'latest released' and then 'upgrading to the contents of the PR' but in this case we are actually downgrading. So what happens is we install 1.55, then upgrade to 1.43, during the 1.55 the GC will delete the DV used for the failing tests, and the test will fail. This was fixed with https://github.com/kubevirt/containerized-data-importer/pull/2434 on main. We should probably check the branch, we are on and not install a version newer than what we are on when running tests.

**Pull request merged**
