### PR TITLE
Increase polling speed for upload annotation test

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
We are seeing failures because the pods are disappearing too fast. Attempt to fix this
by polling much faster so the odds of us being able to get both pods is increased.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
We can also use the rate-limited HTTP url

**Comment by awels** [comment]
We can't since this is an upload.

**Pull request merged**
