### PR TITLE
Adjust alpha deprecation tests

### PR DESCRIPTION
**Pull request by maya-r**
**What this PR does / why we need it**:
Be a bit more eager in testing that a DV from very old version survives unmodified - get a completed DV and make additional modifications, and check that the additional modifications survive.
Fix a small issue that became apparent in scaleDeployment function.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
Not sure why we get storageprofile metric flakes again, the changes don't seem to be related

**Comment by akalenyu** [comment]
/test pull-containerized-data-importer-e2e-destructive
trying to see if it'll reproduce again

**Comment by maya-r** [comment]
Weird... let's try that a second time to be sure
/test pull-containerized-data-importer-e2e-destructive

**Comment by maya-r** [comment]
hasn't failed twice. not sure what that was about, let's try merging it?
/hold cancel

**Comment by maya-r** [comment]
/retest
I'm not concerned about the failure of the ceph test because this PR should only change code for the destructive lane

**Comment by akalenyu** [comment]
> /retest I'm not concerned about the failure of the ceph test because this PR should only change code for the destructive lane

Yeah seen this one happen a few times, suspecting some finalizer race in the populator ecosystem

**Pull request merged**
