### PR TITLE
common: fixed key constants capitalization

### PR DESCRIPTION
**Pull request by danielerez**
Fixed capitalization to correalte with other constants in the file.

### CODE REVIEW

**Comment by danielerez** [comment]
@aglitke @awels @rollandf

**Comment by rollandf** [comment]
I see in a lot of other places that we use mixed caps.
We need to decide for consistency.

**Comment by copejon** [comment]
> We need to decide for consistency.

Agreed.  It'd be best to adhere to go idiom with cameCased const names.

**Comment by j-griffith** [comment]
The Go standard is actually camel case instead of all caps.  I have a patch series that's leading up to those changes.. .something like this  https://gist.github.com/j-griffith/a65e80a2bc008258efe4b2399f0cd636

**Comment by jeffvance** [comment]
> waiting to merge when previous review comments are addressed...
Since kubevirt implements all of golint`'s recommendations I'd say let golint decide. Not being tongue-in-cheek, if golint has an opinion on this then let's follow that recommendation.

**Comment by jeffvance** [comment]
@danielerez Pls work with @j-griffith on this. My opinion as of now is that we should close your pr because of his series of prs that are about to be merged.

**Pull request merged**
