### PR TITLE
Fix typo in operator cluster roles

### PR DESCRIPTION
**Pull request by aglitke**
Signed-off-by: Adam Litke <alitke@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by aglitke** [comment]
@mhenriks Why wouldn't this typo be breaking our deployment?

**Comment by awels** [comment]
> @mhenriks Why wouldn't this typo be breaking our deployment?

I don't think we are using daemonsets in CDI, so there is no need to have this permission?

**Comment by mhenriks** [comment]
@aglitke there are no daemonsets in CDI also, daemonsets are not included in #1012 so this PR should prob be closed

**Comment by MarSik** [comment]
@mhenriks Well, if you do not need the permission then you should probably remove it completely. #1012 does not seem to be touching this one.

**Comment by awels** [comment]
https://github.com/kubevirt/containerized-data-importer/pull/1012/files#diff-afdd9efbf2b4dce118add9994e36486fL185 removes it as far as I can tell.

**Comment by MarSik** [comment]
@awels You are right.. I could not Ctrl-F it in my browser for some reason..

**Comment by awels** [comment]
It was hiding by default because of the big change in that particular file. That is why ctrl-f didn't find it.

**Comment by awels** [comment]
But I think we can close this in favor of #1012 now.

**Comment by aglitke** [comment]
Agreed.

**Pull request closed without merging**
