### PR TITLE
travis: Run unit and functional tests

### PR DESCRIPTION
**Pull request by fabiand**
Signed-off-by: Fabian Deutsch <fabiand@fedoraproject.org>

### CODE REVIEW

**Comment by fabiand** [comment]
This enables to run the functional tests using travis.

This works nicely, just oen test fails IIUIC.

**Comment by jeffvance** [comment]
@screeley44 's pr #89 may fix the test failure.
This looks good to me but I am not knowledgeable on Travis.

**Comment by fabiand** [comment]
It's üretty straight forward, and nothing can go wrong.

The worst is that the tests keep on failing until the test is fixed :9

**Comment by jeffvance** [comment]
lgtm

**Pull request merged**
