### PR TITLE
Forgot to update bazel-build-images when splitting pushing.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
This PR fixes the make bazel-build-images make target.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
/lgtm
but maybe the SonarCloud Code Analysis is right that what we have duplicated could be made into a sher variable (images)

**Comment by awels** [comment]
I have no idea how that is related to this PR.

**Comment by awels** [comment]
@brybacki did it fix your issue?

**Comment by brybacki** [comment]
@awels yes

**Pull request merged**
