### PR TITLE
text corrections and readability improvements

### PR DESCRIPTION
**Pull request by ibesso-rh**
```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
the bot is complaining you haven't `git commit --sign`'d, which adds a line Sign-Off: yourname <youremail> to the commit messages.

**Comment by maya-r** [comment]
Looks good to me otherwise

**Comment by ibesso-rh** [comment]
Thanks for reviewing, Maya.
I opened a draft PR because I did not want to trigger anything before I
will examine the details.

Does this mean that I have to edit the commits in order to add the sign-off
(if that is possible) or should I fork again and commit with the proper
additions?

Furthermore, the reason I did not proceed with the PR is that I noticed
that I might have mistakenly merged my commits, and now I have 6 commits
which are essentially the same 3 commits duplicated (I merged each patch
into my branch already, so perhaps that created the redundancy).

**Comment by maya-r** [comment]
There are a bunch of ways to handle this which produce the same result.
You want to have
(your new changes in a new commit)
  |
(the master branch in the "origin" remote)

To create this you can:
- Fork again, causing you to have the master in the "origin" remote as the master branch locally, then re-do the change manually.
- `git reset origin/master`, which is functionally equivalent to cloning the repository again, then re-do the change manually.
- `git rebase -i HEAD~6`, which is the git-native (read: not the most user friendly) way of re-writing history. That lets you do any combination of "I want to edit this one commit message" (change "pick" to "edit") and "I want to re-order my commits" (move the lines around).

Since all those change the history, when you push, it'll have to be a `git push --force`.

git rebase is worth getting to know, but there's nothing wrong with doing things in the other ways.

**Review by InbarRose — APPROVED** [review]
nice improvements, thanks for taking the time.

**Review by orenc1 — APPROVED** [review]
thanks for fixing the typos!

**Pull request merged**
