### PR TITLE
Update csi-cloning prerequisites

### PR DESCRIPTION
**Pull request by halfcrazy**
**What this PR does / why we need it**:
Update CSI  clone prerequisites and remove the cross storage classes CSI clone limitation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
The CSI clone supports cross storage classes now. See https://github.com/kubernetes-csi/external-provisioner/pull/699

The limitation in CDI was removed in https://github.com/kubevirt/containerized-data-importer/pull/2750/files#diff-6a637cfe899a0436fa6e24865f2b9259f9b8504e40e080e03603830a5504a0c9L754

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
Thanks @halfcrazy!
/lgtm
/approve

**Comment by ShellyKa13** [comment]
@halfcrazy Hi thanks for the PR! you need to add "NONE" at the PR description under "release notes"

**Comment by halfcrazy** [comment]
> @halfcrazy Hi thanks for the PR! you need to add "NONE" at the PR description under "release notes"

Done

**Pull request merged**
