### PR TITLE
Fix SnapshotForSmartCloneInProgress sometimes not occuring

### LINKED ISSUE #2121: [flaky] SmartClone tests [test_id:4987]Verify DataVolume Smart Cloning - volumeMode filesystem - Waits for source to be available
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
Test fails often:
sample here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/2118/pull-containerized-data-importer-e2e-k8s-1.21-ceph/1484242383892647936

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

**What this PR does / why we need it**:
Sometimes we skip SnapshotForSmartCloneInProgress and directly go to
Succeeded.
This happens when the `r.updateDataVolume(dataVolumeCopy)` call fails
(for example, with `the object has been modified; please apply your changes to the latest version and try again`).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2121 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/test pull-cdi-generate-verify

I have not seen this destructive lane failure sequence before

**Comment by brybacki** [comment]
I thin I have seen it. It looks like everything is missing (in CDI). Probably some desctructive test, removed CDI, and cleanup/restore was not successful.

**Comment by akalenyu** [comment]
@awels @brybacki https://github.com/kubevirt/kubevirtci/pull/750 should get rid of the AfterSuite failure in the ceph lane that we have been seeing for quite some time (tested locally)

**Comment by akalenyu** [comment]
> > > @awels @brybacki [kubevirt/kubevirtci#750](https://github.com/kubevirt/kubevirtci/pull/750) should get rid of the AfterSuite failure in the ceph lane that we have been seeing for quite some time (tested locally)
> > 
> > 
> > That is good news!
> 
> Once that merges, we will need to update kubevirtci in our repo to the new version.

ofc, hopefully we get no issues with bumping kubevirtci like last time

**Comment by brybacki** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.21-ceph
Aftersuite again.

**Pull request merged**
