### PR TITLE
Upload API Server

### PR DESCRIPTION
**Pull request by davidvossel**
**IMPORTANT NOTE** The logic to redirect the upload stream to a POD is not implemented in this PR. That is meant to be a follow up. This PR proves out all the logic up to the point of redirecting the stream "somewhere" to be processed. 

# Overview

This PR introduces two new components into CDI, the **cdi-apiserver** and **cdi-uploadproxy**. Both of these components are infinitely horizontally scalable. 

## CDI API server
**cdi-apiserver** Is a stateless Kubernetes aggregated API server that registers itself with the Kubernetes API server as a new REST endpoint.  This allows users to access the cdi-apiserver using standard **kubectl** tooling. When users attempt to access a cdi API object, that request goes through the standard Kubernetes API server and is proxied to our registered cdi-apiserver.

## CDI Upload Proxy
**cdi-uploadproxy** Is a stateless endpoint that accepts and authenticates upload requests with an UPLOAD_TOKEN header. As a follow up to this PR, we will decide where to redirect the upload stream. 

## User Upload Worflow

1. User posts an upload token request to the cluster. The encrypted Token is returned immediately within the response in the status field. The response is stateless. No UploadToken object was stored in persistent storage. The generated token is unique to this request.
```
cat <<EOF | kubectl create -o yaml -f -
> apiVersion: upload.cdi.kubevirt.io/v1alpha1
> kind: UploadToken
> metadata:
>   name: my-token
>   namespace: default
> spec:
>       pvcName: test
> EOF
apiVersion: upload.cdi.kubevirt.io/v1alpha1
kind: UploadToken
metadata:
  creationTimestamp: null
  name: my-token
  namespace: default
spec:
  pvcName: test
status:
  token: eyJlbmNyeXB0ZWREYXRhIjoiUGdBaUdmNjhCZlFjU2cwcTI5dWRDVVBBZjJjTjN5Nzd1MFEyRitETklxdklrT1VSZGVFVjVnYysxaFJxUGVSUHJ2anBEZWdjandQNnVaVit4MEx1aXZYTXlFWmpENjBRZXJBczU3QVNUSi9IMjdsdUZ0ZGJnSW5QZnVvSGROb1NCdUVxdXZkMDRHdURLOFowT1JUQTJyRHcxa0EvQnRPTHA4QTdhdkxFR3ErMXZlenV0MWhXVExpZjFQRllXR2FZcVNhcjZ5enRLakVrS2hVRTF4NUxvK3FPNXVJb0NSbUt4b2ZmNXBuZHNJdjdYSXNuK0JSeE1PRGR0Rm82ZVZTbldGeXVweGVEMHhCc3VvSzhNOHhpZ0p2ZGYzMXhrREdHM2NLN2tjNEJtdWtYa2E0NDVoOUZFOEt6SUtES3QwTlZSaGh0R1RpOTYxVFVsc2dCZkRoekpRPT0iLCJzaWduYXR1cmUiOiJEcjNSQjJVR1pQZXJYelRkOExCMTlRT3JsaGxNOE9zQWt6TnQ3UC8rUDV1akxuUi9Qc2F6a0ZMSkZuRjdnK3FMZy9pYWJ2Uy9KU0U3eGluSVNzZDdIaXRXTklwUWpETElhdjBSaCtDTW1uUG9BYTBXSjBYL1o3Q0NpdXBXU1RTbkcreG82Z1MycjlYaVlHd0RaRnpMdmpJcVNveEdVTzhCcU1MQ3VTb0FrTEE3UUVqVm9zWnFycjFLSFFnSW9oanEzNTBINjBXRUFFOVdxWmx6b3BUYnFFaEFaSGRTaVV0WjlvN0RCK0JMS0FMdGpuUnZFK1VUcVFHV2FZLzY0L0I0czN1R0dVZXBFNjFOSkFkZU5rQVJjd1JWbU5vTTdIemlBVkZGbTBXa21lRTZPdFFZUElKNlRsNkdLRURiK3dGZ2djN0l1TnVNSytBUXZkbDB1SnE0MVE9PSJ9

```

2. User places the token in the **UPLOAD_TOKEN** header of a curl request to the upload proxies /v1alpha1/upload endpoint

```
curl -v -k -H "UPLOAD_TOKEN: $token" https://my.upload.proxy.dns/v1alpha1/upload
```

From there the upload proxy handles verifying the token to ensure the user has permissions to perform the upload, and then redirects the upload stream internal to the cluster "somewhere" (we haven't determined that part yet)

## User Authentication and Authorization

Users are authenticated and authorized before being allowed to create an UploadToken.

Authentication is performed by the Kubernetes API server during the creation of the UploadToken. Once the user is authenticated, the Kubernetes API server forwards the request with auth headers to the cdi-apiserver. 

Authorization is performed by the cdi-apiserver through the use of an authorization review request. The cdi-apiserver knows the user when the request comes in, and uses that information to call back into the Kubernetes API server to verify the user is authorized via RBAC to create an UploadToken.

If both authn/authz pass, a valid token is returned to the user. 

## UploadToken Authentication

Both the cdi-apiserver and cdi-uploadproxy components generate an RSA key pair the first time they run. 

A token generated by the cdi-apiserver is encrypted with the cdi-uploadproxy's public key, and signed by the cdi-apiserver's private key. 

When the token is presented to the cdi-uploadproxy, that proxy decrypts the token using its private key, and verifies the origin of the token's signature with the cdi-apiserver's public key.

This means only the uploadproxy can decrypt a token, and only an apiserver can sign the token. If the upload proxy can both decrypt and verify the signature, then the upload proxy knows the token originated from the cdi-apiserver and is valid. 

## UploadToken Expiry

UploadTokens have a creation timestamp and are only valid for 5 minutes after creation. This prevents the ability to replay an UploadToken later.

## UploadProxy TLS Certs

At the moment the UploadProxy generates selfsiged certs.  This means clients uploading data to the UploadProxy will either have to ignore the authenticity of the selfsigned cert, or we'll need to generate certs based on the k8s CA for the UploadProxy in the future. I've left this as a followup item for now. 

# UploadTokens vs Service Account Bearer Tokens

One aspect of the Upload API design that I contemplated alternatives to is whether or not to use a UploadToken (which we implement) or a Service Account Bearer Token (which is a k8s concept) for authn/authz.

I ended up taking the UploadToken approach and I’ll explain my rational. 

Kubernetes provides users the ability to authenticate with a cluster using multiple backends such as oauth, x.509 certs, OICD, and more. We definitely don’t want our UploadProxy involved with any of those backends. The only way of authenticating that the UploadProxy can tap into is the concept of a ServiceAccount’s bearer token. ServiceAccounts are how components within the cluster authenticate with the apiserver to perform actions like retrieving pod information. There’s an api that lets us authenticate a bearer token with the k8s apiserver in order to verify a user’s identify. 

Here’s the problem I ran into though. Depending on how users authenticate with a cluster, they may or may not have a service account associated with them.  For example, in my development cluster I authenticate with an x.509 cert and not a bearer token. There’s no bearer token readily available for me to use either. For me to get a bearer token I’d have to create a ServiceAccount plus assign a ClusterRole to that service account with the correct RBAC rules, and then retrieve the ServiceAccount’s bearer token from a secret. At that point I’d have a bearer token I could place in a header during the upload request. The UploadProxy would then have to call back into the k8s apiserver to verify the token before I’d be authenticated.

With the UploadToken I’ve removed the requirement for a ServiceAccount’s bearer token to be involved at all. We have a workflow that will work 100% the same regardless of how users authenticate with the cluster. Any user who can authenticate with the k8s API server and is authorized to create an UploadToken has an immediate path for performing the upload. 

# Remaining Tasks
- [x] token encrypt/decrypt unit tests
- [x] apiserver unit tests
- [x] uploadproxy unit tests
- [x] authorization unit tests

### CODE REVIEW

**Comment by davidvossel** [comment]
Here's a tip about how to view these changes in GitHub without having to see all the vendoring and boilerplate api generated code.

When looking at the patches, in the top left theres a **Changes From** drop down. Select all the comments except for the first two and you'll be able to see the logic this patch implements.

**Comment by davidvossel** [comment]
I'm removing the [WIP] tag now that I've finished the remaining unit tests.

**Comment by jeffvance** [comment]
@davidvossel this is **very** well documented -- thanks. But would you mind adding a paragraph on the reasons you rejected k8s built-in bearer tokens?

**Comment by davidvossel** [comment]
> would you mind adding a paragraph on the reasons you rejected k8s built-in bearer tokens?

I added my rational to the description

**Comment by simo5** [comment]
Please use something like a JWT instead of inventing your own token.

**Comment by davidvossel** [comment]
> Please use something like a JWT instead of inventing your own token.

agreed, sounds good

**Comment by aglitke** [comment]
Is the PR superceded by #381 and able to be closed?

**Comment by davidvossel** [comment]
yes, #381 is the new pr

**Pull request closed without merging**
