### PR TITLE
Fixing CDIStatus generate-verify issues

### PR DESCRIPTION
**Pull request by jakub-dzon**
**What this PR does / why we need it**:
This PR fixes errors reported by the generate-verify Makefile verb

**Special notes for your reviewer**:
The `kubevirt.io/controller-lifecycle-operator-sdk` replacement in go.mod will be removed once fix in that module is merged.

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Comment by jakub-dzon** [comment]
@awels - please have a look again; LGTM label has been removed

**Pull request merged**
