### PR TITLE
don't run as root

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**: For increased security, don't run our applications as root when possible.  As far as I can tell, we only need root for host assisted cloning and import/upload to a block pvc.  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
@mhenriks What is the status of this?

**Comment by mhenriks** [comment]
@awels - forgot about this, should be good to go

**Comment by mhenriks** [comment]
ci test please

**Comment by mhenriks** [comment]
@awels I think this is good to go if you want to take another look.

**Pull request merged**
