### PR TITLE
Retry adding ticket on imageio container startup

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

**What this PR does / why we need it**:
Sometimes we see that ticket is not there (thx awels), we might want to
try a few times before giving up.
With `&&` if the add-ticket command fails, the container will keep restarting.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/test all

warm import failure again (non-related)

**Comment by awels** [comment]
I have noticed with an increased CI load, there is an increase in the warm migration failure. We had disabled one of them for a while, and I thought I had fixed the dead lock, but there is another race.

**Comment by akalenyu** [comment]
@awels We never backported this, should we?

**Comment by akalenyu** [comment]
> Is there a need? are we getting failures?

Think I am seeing this, yes, it should be possible to hit this in all releases but I'd start with 4.10

**Pull request merged**
