### PR TITLE
Call finalize in close for imageio source

### PR DESCRIPTION
**Pull request by machacekondra**
**What this PR does / why we need it**:
By calling Finalize method in Close method of the imageio source
we will make sure we finalise the import immediately, rather then
rely on implicit finalise of imageio, which is based on timeout.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Explicitly finalise image transfer connection instead of let it timeout for imageio datasource.
```

### CODE REVIEW

**Comment by machacekondra** [comment]
cc @pkliczewski

**Comment by awels** [comment]
Can you add a release note? Or NONE if there is no release note, but I think it is worth mentioned an enhancement to finalize the imageio connection instead of letting it time out.

**Comment by machacekondra** [comment]
> Can you add a release note? Or NONE if there is no release note, but I think it is worth mentioned an enhancement to finalize the imageio connection instead of letting it time out.

I've updated the release note.

**Comment by awels** [comment]
looks like you have a linter error, make test-lint will show you

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-os-3.11.0-crio
Error was a fedora mirror not resolving
Error downloading [http://download.fedoraproject.org/pub/fedora/linux/releases/31/Everything/x86_64/os/Packages/l/lvm2-2.03.05-2.fc31.x86_64.rpm] to /root/.cache/bazel/_bazel_root/e03bf9038fc5089c0dbc8615812d9838/external/lvm2/file/downloaded: Unknown host: dl.iad2.fedoraproject.org

**Pull request merged**
