### PR TITLE
Updated controller-lifecycle-operator-sdk dependency

### LINKED ISSUE #1380: Move controller-lifecycle-operator-sdk imports from github.com to kubevirt.io
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

 controller-lifecycle-operator-sdk imports currently root at github.com.  Should be kubevirt.io

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by jakub-dzon**
**What this PR does / why we need it**:
module github.com/kubevirt/controller-lifecycle-operator-sdk was renamed to kubevirt.io/controller-lifecycle-operator-sdk

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1380

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
you need to rebase on master, that lane is failing because we added a random cr name on it. There is a bug that got fixed that you are hitting right now.

**Comment by jakub-dzon** [comment]
Thanks for the hint!

**Comment by jakub-dzon** [comment]
@awels - actually, it is up-to-date with master

**Comment by jakub-dzon** [comment]
From what I see, other, passing, lanes don't use `RANDOM_CR=true`

**Comment by jakub-dzon** [comment]
@awels: I think the problem is that initially CDI is installed from the latest release (not generated manifest), where the config CR name is `cdi` and the scripts wait for cr with a generated name, which won't be there.

**Comment by awels** [comment]
Hmm, okay if it is doing that, that would be a problem, it should only be upgrading from a previous release, if the appropriate environment variable is set. Let me investigate.

**Comment by awels** [comment]
Okay, yeah, we are always upgrading from latest release to current PR. Which we shouldn't do in that particular case. I created #1391 to not upgrade if the flag is set.

**Comment by awels** [comment]
It merged, so a rebase should fix the ceph lane

**Comment by jakub-dzon** [comment]
@awels - thanks, it worked!

**Comment by awels** [comment]
@mhenriks This lgtm can you give it a quick review?

**Pull request merged**
