### PR TITLE
Update fedora 33

### PR DESCRIPTION
**Pull request by alicefr**
Update fedora version to 33

**What this PR does / why we need it**:
Needed for new nbdkit filters and plugins not available in fedora 31

**Release note**:
<!--  Write your release note:
Update to fedora 33
```release-note
none
```

### CODE REVIEW

**Comment by alicefr** [comment]
I still have some doubt how to update to fedora 33. I'm not sure how to deal with the [2 fedora images](https://github.com/kubevirt/containerized-data-importer/blob/master/WORKSPACE#L94-L108). Right now, both refer to the fedora image 33 in Docker Hub. Second, I haven't included the mirror to `http://mirror.isoc.org.il`, because it is not there for all the packages. Please, let me know if I need to modify them. I can also put this PR as WIP. Thanks!

**Comment by maya-r** [comment]
I added the mirror.isoc.org.il back when we had a short lapse in mirroring to the google storage and some of the test clusters were defaulting to a bad mirror. No problem to leave it out.
/ok-to-test

By the way, what is pulling in liburing?

**Comment by alicefr** [comment]
> By the way, what is pulling in liburing

The dependency is needed by qemu-img

**Comment by alicefr** [comment]
> I still have some doubts about how to update to fedora 33. I'm not sure how to deal with the [2 fedora images](https://github.com/kubevirt/containerized-data-importer/blob/master/WORKSPACE#L94-L108). Right now, both refer to the fedora image 33 in Docker Hub. 

Any suggestions, for the first question I raised? I could merge the 2 images into a single one.

**Comment by maya-r** [comment]
Not sure why the second image varies. It seems to be only used by the ember CSI lane which isn't enabled right now. It's probably fine to not test this variation because it might have additional issues.

**Comment by alicefr** [comment]
I also updated the `hack/build/docker/builder/Dockerfile` to fedora 33.

**Comment by alicefr** [comment]
@maya-r any concerns about this PR?

**Comment by alicefr** [comment]
There is an issue with the new image `hack/build/docker/builder/Dockerfile`. Upgrading to fedora 33 leads to a rsync issue:
```bash
export BUILDER_IMAGE="kubevirt/kubevirt-cdi-bazel-builder:fedora-33"
]$ make test-unit
./hack/build/bazel-docker.sh "./hack/build/run-unit-tests.sh ./pkg/... ./cmd/..."
Making sure output directory exists...
go version go1.14.6 linux/amd64
Starting rsyncd

Rsyncing /home/afrosi/go/src/kubevirt.io/containerized-data-importer to container
rsync: [receiver] failed to set permissions on "/.WORKSPACE.ILtBGp" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/.git/.HEAD.PDE50o" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/.git/.index.8NvYgp" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/.git/logs/.HEAD.08XqRp" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/cmd/cdi-importer/.BUILD.bazel.8Krizn" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/cmd/cdi-uploadserver/.BUILD.bazel.nK7Wbo" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/hack/build/docker/builder/.Dockerfile.Jnlfbp" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/tools/cdi-func-test-file-host-init/.BUILD.bazel.kGINCr" (in build): Operation not supported (95)
rsync: [receiver] failed to set permissions on "/tools/cdi-func-test-registry-init/.BUILD.bazel.eglqfn" (in build): Operation not supported (95)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1330) [sender=3.2.3]
make: *** [Makefile:65: test-unit] Error 23

```
The CI is not catching it because it doesn't try the new image. So, to upgrade to fedora 33 will break the tests :'( . I'll dig into the issue

**Comment by awels** [comment]
So in order to try the new fedora 33 for the builder, you need to create a separate PR that updates https://github.com/kubevirt/containerized-data-importer/blob/master/hack/build/config.sh#L29 to a new tag and includes the new Dockerfile. That should all pass as nothing has changed. Once that is merged, a new hash will be produced, then in this PR update L30 of the same file to use the new tag. The build system will then start using the new fedora image.

**Comment by alicefr** [comment]
many thanks, @awels! I'll remove the last commit and open a second PR. Even if the rsync problem will still fail. I have tried with a very simple Dockerfile like this:
```dockerfile
FROM fedora:31/33

RUN dnf update -y && dnf install -y \
        rsync-daemon \
        rsync \
	&& dnf clean all
COPY rsyncd.conf /etc/rsyncd.conf

```
and then I tried to rsync the repo, and with fedora 31 is succeeding and 33 is failing. The problem is aso that in both fedora version the rsync package is the same version `rsync  version 3.2.3  protocol version 31`

**Comment by alicefr** [comment]
Opened a new PR #1511 to update the builder and removed the commit for updating the Dockerfile of the builder

**Comment by alicefr** [comment]
I had to update the PR because one of the rpms was updated to a new version. It was `xen-libs-4.14.0-9` to `xen-libs-4.14.0-12`. This is however very unreliable :/

**Comment by awels** [comment]
Once merged, we have process that copies all the rpms into a known location, after which it is very stable. Because it will fall back to that location if the rpm is not found.

**Comment by alicefr** [comment]
Ok, it seems I have to reupdate all the rmps. I'll do it and push the updates

**Comment by alicefr** [comment]
Updated the rpm versions and sha, updated also the sha for the new builder image. The new `kubevirt/kubevirt-cdi-bazel-builder` is based on fedora 33. Fedora 33 has an issue with the glibc libraries and this causes a problem in setting the permissions wih rsync. That's why I changed the flag for rsync. More details in this [BZ1904344](https://bugzilla.redhat.com/show_bug.cgi?id=1904344) and [BZ1894485](https://bugzilla.redhat.com/show_bug.cgi?id=1894485)

**Comment by alicefr** [comment]
:thinking: the CI is still failing so I'm probably missing something

**Comment by awels** [comment]
Yeah looks like the rsync issue is still present.

**Comment by alicefr** [comment]
Ok, another try! I removed the 'E'. When I tried locally, I forgot to clean up the `kubevirt-cdi-volume` volume

**Comment by alicefr** [comment]
:sob: it doesn't work. I tried to clean up containers and volumes, and on my fedora 33, it's working. I cannot reproduce the failure

**Comment by alicefr** [comment]
Using `focal` as distro makes travis much more happy :partying_face:

**Comment by alicefr** [comment]
@awels @maya-r now the CI looks greener than before :). Could you please retrigger the failing test suite and maybe have a look if the workaround for the permissions seems fine to you. Many thanks

**Comment by awels** [comment]
Looks fine to me, only question I have is, why do we need device mapper in the registry container?

**Comment by alicefr** [comment]
it's needed by `buildah`

**Comment by alicefr** [comment]
The [BZ 1904344](https://bugzilla.redhat.com/show_bug.cgi?id=1904344) has been solved and the fix is not available in fedora 33. I'll open a second PR to trigger the build for `kubevirt/kubevirt-cdi-bazel-builder`. Hence, we don't need anymore to change the permissions.

**Comment by alicefr** [comment]
@maya-r I saw that you substituted `http://download.fedoraproject.org/pub/fedora` with `http://archives.fedoraproject.org/pub/archive` #1529. Should I do the same for upgrading to fedora 33?

**Comment by maya-r** [comment]
No, just wanted the release branch to build despite the URLs receiving 404.

**Comment by alicefr** [comment]
Could you please retrigger the tests? Or am I allowed to do it? Many thanks

**Comment by maya-r** [comment]
I assume that it would work if you did it too
/retest

**Comment by alicefr** [comment]
Now that the CI is happy. Any concerns with this PR? :) Please note that I removed the rsync workaround as the fix is already available in the rsync fedora 33 package

**Pull request merged**
