### PR TITLE
Fixing dependency on Operator Framework.

### PR DESCRIPTION
**Pull request by tomob**
Required through Operator Lifecycle Manager.

Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>

**What this PR does / why we need it**:

A pulled version of OF has a dependency to a repository which no longer exists.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Ahhh you found how to fix the issue then? Does this mean the other PR can be closed?

**Comment by tomob** [comment]
> Ahhh you found how to fix the issue then? Does this mean the other PR #1386 can be closed?

Yes, I think so. This one is definitely better that #1386.

**Comment by awels** [comment]
So the semver was causing the issue?

**Comment by tomob** [comment]
> So the semver was causing the issue?

No, it needs to be changed because of the change in the dependencies.

**Comment by awels** [comment]
Gotcha. Seems like we just merged something that is causing a conflict.... I see no issues with the PR was just wondering about the changes in the semver

**Pull request merged**
