### PR TITLE
Update kubevirtci and add k8s-1.18 lane

### PR DESCRIPTION
**Pull request by maya-r**
We'd like to switch our k8s-1.16 lanes with k8s-1.18 lanes. This is the first step towards this.
We need a newer kubevirtci for a k8s-1.18 lane.
Adding cluster-sync logic too (copied directly from k8s-1.17 with no changes) 

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
@maya-r kubevirt ci is updated by updating the revision here and running `make generate`:  https://github.com/kubevirt/containerized-data-importer/blob/master/hack/update-codegen.sh#L59

**Comment by awels** [comment]
yeah just update the hash to the latest git hash from kubevirtci master, and run make generate. There should be more changes than this here. This keeps our cluster-up in sync with everyone else.

**Comment by maya-r** [comment]
Thanks. This one is with `make generate`, it doesn't look too different.

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.16-nfs
flaky fedora mirror

**Pull request merged**
