### PR TITLE
Fix that the Resources configuration is missing the configuration of …

### PR DESCRIPTION
**Pull request by mzzgaopeng**
**What this PR does / why we need it**:
Fix that the Resources configuration is missing the configuration of the initcontainer container

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/kubevirt/containerized-data-importer/issues/1043
**Special notes for your reviewer**:

**Release note**:

```release-note
Fix that the Resources configuration is missing the configuration of the initcontainer container

  initContainers:
  - command:
    - sh
    - -c
    - cp /usr/bin/cdi-containerimage-server /shared/server
    image: quay.io/kubevirt/cdi-importer:v1.58.0
    imagePullPolicy: IfNotPresent
    name: init
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 107
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /shared
      name: shared-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-csqcd
      readOnly: true
```

### CODE REVIEW

**Comment by akalenyu** [comment]
Hey, thanks, the approach makes sense
Can you please sign your commit, for example, with `git commit --amend -s`

**Comment by akalenyu** [comment]
Also if you can add a unit test in `pkg/controller/import-controller_test.go` that checks the pod gets created correctly, that would be awesome :pray:
You should be able to update the CDIConfig object with resources as it's already a part of the unit test environment

**Review by mzzgaopeng — COMMENTED** [review]
Fix that the Resources configuration is missing the configuration of the initcontainer container

Signed-off-by: lion <mzzgaopeng@gmail.com>

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# Date:      Wed Jan 3 16:12:09 2024 +0800
#
# On branch release-v1.58
# Your branch is ahead of 'github/release-v1.58' by 1 commit.
#   (use "git push" to publish your local commits)
#
# Changes to be committed:
#       modified:   pkg/controller/import-controller.go
#
# Untracked files:
#       .DS_Store
#       vendor/.DS_Store
#

**Comment by akalenyu** [comment]
oh and btw, and we usually develop on the `main` branch and only backport to release branches once things are merged there.
so I think you can just change the target branch on the pull request

**Comment by mzzgaopeng** [comment]
> Hey, thanks, the approach makes sense Can you please sign your commit, for example, with `git commit --amend -s`

how to sign my commit？

**Comment by akalenyu** [comment]
> git commit --amend -s

`git commit --amend -s` Should work

**Comment by akalenyu** [comment]
> > Hey, thanks, the approach makes sense Can you please sign your commit, for example, with `git commit --amend -s`
> 
> how to sign my commit？

`git commit --amend -s` Should work

**Comment by mzzgaopeng** [comment]
> > > Hey, thanks, the approach makes sense Can you please sign your commit, for example, with `git commit --amend -s`
> > 
> > 
> > how to sign my commit？
> 
> `git commit --amend -s` Should work

The signature information has been submitted. Do you still need to submit the test cases？

**Comment by akalenyu** [comment]
> > > > Hey, thanks, the approach makes sense Can you please sign your commit, for example, with `git commit --amend -s`
> > > 
> > > 
> > > how to sign my commit？
> > 
> > 
> > `git commit --amend -s` Should work
> 
> The signature information has been submitted. Do you still need to submit the test cases？

Yes, that would be great, thank you

**Comment by mzzgaopeng** [comment]
> > > > > 嘿，谢谢，这种方法很有意义，您能否签署您的承诺，例如，`git commit --amend -s`
> > > > 
> > > > 
> > > > 如何签署我的提交？
> > > 
> > > 
> > > `git commit --amend -s`应该管用
> > 
> > 
> > 签名信息已提交。还需要提交测试用例吗？
> 
> 是的，那就太好了，谢谢 您能否将目标分支也更改为`main`？ 图像

Do I need to resubmit a PR？

**Comment by awels** [comment]
@mzzgaopeng The PR needs a rebase if you could do a rebase that would be great.

**Comment by mzzgaopeng** [comment]
There are a lot of changes in rebase, how to merge it into main again?

**Comment by mzzgaopeng** [comment]
> There are a lot of changes in rebase, how to merge it into main again?

update to [https://github.com/kubevirt/containerized-data-importer/pull/3157](url)

**Comment by akalenyu** [comment]
> > There are a lot of changes in rebase, how to merge it into main again?
> 
> update to [https://github.com/kubevirt/containerized-data-importer/pull/3157](url)

thanks! we will use the bot to cherry pick
/close

**Pull request closed without merging**
