### PR TITLE
Fix that the Resources configuration

### PR DESCRIPTION
**Pull request by mzzgaopeng**
**What this PR does / why we need it**:
Fix that the Resources configuration is missing the configuration of the initcontainer container

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/kubevirt/containerized-data-importer/issues/1043
**Special notes for your reviewer**:

**Release note**:

```release-note
Fix that the Resources configuration is missing the configuration of the cdi-containerimage-server initcontainer container
```

### CODE REVIEW

**Comment by akalenyu** [comment]
@mzzgaopeng looks like unit tests need some adaptations:
```bash
[38;5;13mIn [1m[It][0m[38;5;13m at: [1m/gimme/.gimme/versions/go1.21.5.linux.amd64/src/runtime/panic.go:261[0m [38;5;243m@ 03/28/24 10:43:22.593[0m

  [38;5;13mruntime error: invalid memory address or nil pointer dereference[0m

  [38;5;13mFull Stack Trace[0m
    kubevirt.io/containerized-data-importer/pkg/controller.makeImporterInitContainersSpec(0xc000a4fde8)
    	/root/go/src/kubevirt.io/containerized-data-importer/pkg/controller/import-controller.go:1098 +0x559
```
since they pass `nil` to `args.podResourceRequirements`

**Comment by mzzgaopeng** [comment]
> @mzzgaopeng looks like unit tests need some adaptations:
> 
> ```shell
> �[38;5;13mIn �[1m[It]�[0m�[38;5;13m at: �[1m/gimme/.gimme/versions/go1.21.5.linux.amd64/src/runtime/panic.go:261�[0m �[38;5;243m@ 03/28/24 10:43:22.593�[0m
> 
>   �[38;5;13mruntime error: invalid memory address or nil pointer dereference�[0m
> 
>   �[38;5;13mFull Stack Trace�[0m
>     kubevirt.io/containerized-data-importer/pkg/controller.makeImporterInitContainersSpec(0xc000a4fde8)
>     	/root/go/src/kubevirt.io/containerized-data-importer/pkg/controller/import-controller.go:1098 +0x559
> ```
> 
> since they pass `nil` to `args.podResourceRequirements`

Sorry, the code submitted yesterday was submitted incorrectly and has been resubmitted.

**Comment by akalenyu** [comment]
> > @mzzgaopeng looks like unit tests need some adaptations:
> > ```shell
> > �[38;5;13mIn �[1m[It]�[0m�[38;5;13m at: �[1m/gimme/.gimme/versions/go1.21.5.linux.amd64/src/runtime/panic.go:261�[0m �[38;5;243m@ 03/28/24 10:43:22.593�[0m
> > 
> >   �[38;5;13mruntime error: invalid memory address or nil pointer dereference�[0m
> > 
> >   �[38;5;13mFull Stack Trace�[0m
> >     kubevirt.io/containerized-data-importer/pkg/controller.makeImporterInitContainersSpec(0xc000a4fde8)
> >     	/root/go/src/kubevirt.io/containerized-data-importer/pkg/controller/import-controller.go:1098 +0x559
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > since they pass `nil` to `args.podResourceRequirements`
> 
> Sorry, the code submitted yesterday was submitted incorrectly and has been resubmitted.

no worries, thank you!
/test all

**Comment by akalenyu** [comment]
/test pull-containerized-data-importer-e2e-ceph
@0xFelix may be same symptom as the other flake we saw

**Pull request merged**
