### PR TITLE
Stop Using Deprecated Packages

### PR DESCRIPTION
**Pull request by nunnatsa**
sigs.k8s.io/controller-runtime/pkg/runtime/* packages are deprecated, and were moved to new paths.

Trying to upgrade sigs.k8s.io/controller-runtime to version v0.7.0 in HCO created a conflict because in v0.7.0 the deprecated packages were removed and cannot be used.

This PR replaces the deprecated packages with their new paths.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
missing a change to go.mod and go.sum? the way we update also involves invoking `make deps-update`

**Comment by nunnatsa** [comment]
> missing a change to go.mod and go.sum? the way we update also involves invoking `make deps-update`

Thanks for the tip. Was naive to just run `go mod tidy & go mod vendor`.

**Comment by maya-r** [comment]
I'm confused about why there are still no changes to go.mod and go.sum

**Comment by maya-r** [comment]
oh, the packages have a way to write code that works on both versions, got it.

**Comment by nunnatsa** [comment]
> oh, the packages have a way to write code that works on both versions, got it.

Yes, The `runtime/* ` packages were are deprecated and were moved to a new locations. in version 0.7.0 they are removed.

**Comment by awels** [comment]
Why would HCO care about internals of CDI? I am not opposed to this PR at all. But I want to understand why HCO had a conflict. The HCO should be using the generated CDI client and not care about the internals of CDI.

**Comment by nunnatsa** [comment]
> Why would HCO care about internals of CDI? I am not opposed to this PR at all. But I want to understand why HCO had a conflict. 

HCO need to build a CDI object and create/update it in K8s. So HCO uses CDI data types.

> The HCO should be using the generated CDI client and not care about the internals of CDI.
Well, it does not

**Pull request merged**
