### PR TITLE
datavolume_test: skip test 2555

### PR DESCRIPTION
**Pull request by danielerez**
Test 2555[1] (on 'Verify DataVolume' tests) is failing on tier1 cnv 2.1 test.
The issue reproduces when using ubi8 cdi-importer container (see bz#1739149[2]).

I.e. when using 'qemu-img info' on the invalid qcow file[3] (using uni8.1, qemu-img 3.1.0):
$ qemu-img info afl1.img
image: afl1.img
file format: raw
virtual size: 9.5K (9728 bytes)
disk size: 12K
$ qemu-img --version
qemu-img version 3.1.0 (qemu-kvm-3.1.0-30.module+el8.0.1+3755+6782b0ed)

Whereas, using fedora 30 (qemu-img 4.1.0):
$ qemu-img info afl1.img
file format: qcow
virtual size: 152 TiB (167125767422464 bytes)
disk size: unavailable
cluster_size: 4096
$ qemu-img --version
qemu-img version 4.1.0 (qemu-4.1.0-4.fc30)

As 'raw' file format is returned on el8, the supported format validation
isn't failing (on 'qemu.go -> isSupportedFormat), so the import is
completed successfully instead of failing.
Hence, removing this test for now as that file can't be validated
consistently on all envs.

[1] test_id:2555 ('fail creating import dv: invalid qcow large size')
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1739149#c2
[3] https://bugs.launchpad.net/ossa/+bug/1449062/+attachment/4385683/+files/afl1.img

Change-Id: Iadc7a2129cb64a97b0f55dc1553f6a03c0a66ffd
Signed-off-by: Daniel Erez <derez@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Besides the CI system failing for some reason, there is a problem:
```
# kubevirt.io/containerized-data-importer/tests [kubevirt.io/containerized-data-importer/tests.test]
tests/datavolume_test.go:48:2: invalidQcowLargeSizeURL declared and not used
```
The tests failed to compile

**Comment by danielerez** [comment]
> Besides the CI system failing for some reason, there is a problem:
> 
> ```
> # kubevirt.io/containerized-data-importer/tests [kubevirt.io/containerized-data-importer/tests.test]
> tests/datavolume_test.go:48:2: invalidQcowLargeSizeURL declared and not used
> ```
> 
> The tests failed to compile

Right, fixed.

**Comment by awels** [comment]
So the PR itself is fine. I have an issue with solving the problem of the test failing on certain versions of qemu-img by removing the test. In this case the test found an actual problem in qemu-img and we reported it. Personally I would feel more comfortable if we had a mechanism to selectively disable these kinds of tests instead of removing them.

**Comment by danielerez** [comment]
> So the PR itself is fine. I have an issue with solving the problem of the test failing on certain versions of qemu-img by removing the test. In this case the test found an actual problem in qemu-img and we reported it. Personally I would feel more comfortable if we had a mechanism to selectively disable these kinds of tests instead of removing them.

We can mark the test as pending to skip it: https://onsi.github.io/ginkgo/#pending-specs
Haven't found another mechanism in ginkgo unless we want to manually use 'Skip()' in code in some conditions. But not sure it can be done with table driven tests, or if worth the effort for a single test. What do you think?

**Comment by awels** [comment]
You can do FEntry to focus a particular entry in a table, so would PEntry work?

**Comment by danielerez** [comment]
> You can do FEntry to focus a particular entry in a table, so would PEntry work?

Sure, P or X should mark it as pending, but it's hardcoded. We can add it for now instead of removing the test.

**Pull request merged**
