### PR TITLE
Ensure expectation keys are deleted when object is deleted from cluster

### PR DESCRIPTION
**Pull request by davidvossel**
We're supposed to be cleaning up the expectation keys as objects are deleted from the cluster.

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
Looks like the linter failed your patch, as well as the duplicate cloner pod issue.

**Comment by davidvossel** [comment]
retest this please

**Comment by davidvossel** [comment]
ci test please

**Comment by davidvossel** [comment]
fixed the ci issue. It was actually a failing unit test.

**Pull request merged**
