### PR TITLE
change jinjia var name to make it more consistent

### PR DESCRIPTION
**Pull request by shiywang**
**What this PR does / why we need it**:
related to https://github.com/kubevirt/kubevirt-ansible/pull/389  https://github.com/kubevirt/kubevirt-ansible/pull/377

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jeffvance** [comment]
> Please also update the README.md to contain the renamed variable names.

+1

**Comment by shiywang** [comment]
@jeffvance @awels PTAL

**Comment by shiywang** [comment]
@awels once this merged, could you rebuild the manifest and push to the v1.2.0-alpha.1 release page?

**Comment by jeffvance** [comment]
lgtm

**Pull request merged**
