### PR TITLE
Add go.mod to pkg/apis and remove alpha api

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Make it easy to import CDI API types.  Also finally deleting alpha API.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Remove alpha API
```

### CODE REVIEW

**Comment by brybacki** [comment]
Is there a plan to export this to external API specific repo?

**Comment by brybacki** [comment]
```
deployment.apps/cdi-operator configured
configmap/cdi-operator-leader-election-helper unchanged
The CustomResourceDefinition "cdis.cdi.kubevirt.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
make: *** [Makefile:116: cluster-sync-cdi] Error 1
```

**Comment by mhenriks** [comment]
@brybacki yeah there is an upgrade issue to figure out.  The CRD tracks all versions that ever existed.  Even if the resources no longer exist.  Or have already been updated from alpha to beta (happens automatically first time a CDI resource is updated).  `v1alpha1` has to be removed from the CRD `status.storedVersions` list BUT that list cannot be updated by kubectl because the status subresource is enabled for CRDs.

Solutions outlined here:  https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#upgrade-existing-objects-to-a-new-stored-version

**Comment by mhenriks** [comment]
Decided to go a different route

**Pull request closed without merging**
