### PR TITLE
Make reverse proxy send error messages to klog and to virtctl

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**What this PR does / why we need it**:
Upload proxy uses the `httputil.ReverseProxy`.

When `httputil.ReverseProxy` fails, it sends a message down the standard library's default logger. This can be seen in the pod's log but the client simply receives a 5xx error and no context.

This PR redirects messages away from the standard logger and into both the k8s logger and the client.

**Changes in virtctl output**
BEFORE
```
unexpected return value 502,
```
AFTER
```
unexpected return value 502, error in upload-proxy: http: proxy error: dial tcp 10.101.34.134:443: connect: connection timed out
```

**Changes in upload-proxy logs**
BEFORE
```
2024/05/09 16:30:08 http: proxy error: dial tcp 172.30.111.109:443: connect: connection timed out
```
AFTER
```
E0605 11:02:45.551559       1 uploadproxy.go:323] Error in reverse proxy: http: proxy error: dial tcp 10.101.34.134:443: connect: connection timed out
```

**Which issue(s) this PR fixes**
https://issues.redhat.com/browse/CNV-41624

**Special notes for your reviewer**:

**Release note**:
```release-note
Improve error reporting in upload-proxy
```

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
To exercise this fix you need a VM image, then you can run this script:
```
IMAGE=./cirros-0.6.2-x86_64-disk.img

# Start cluster
make cluster-up
make cluster-sync

# Patch cluster (Solved in https://github.com/kubevirt/containerized-data-importer/pull/3306)
host_port=$(./cluster-up/cli.sh ports uploadproxy | xargs)
override="https://127.0.0.1:$host_port"
kubectl patch cdi cdi --type merge -p '{"spec": {"config": {"uploadProxyURLOverride": "'"$override"'"}}}'

# Break the uploadproxy
cat << EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: default-deny-ingress
spec: 
  podSelector: {}
  policyTypes: 
  - Ingress
EOF

# Exercise the error
virtctl image-upload dv hello-example --size=1Gi --image-path "${IMAGE}" --force-bind --insecure
```

**Review by awels — APPROVED** [review]

**Pull request merged**
