### PR TITLE
test fix: Move check of clone type before create target pvc

### PR DESCRIPTION
**Pull request by ShellyKa13**
The test is a negative test that creates the sourcepvc, create a pod to keep it busy, then creates the clone dv which can't do the clone yet since the source is busy. then it creates the targetpvc and expects eventually that the clone will fail since there already exists a pvc with the target name.
now the test after creating the target pvc checks for the clone type annotation on the dv. if the target pvc was created fast enough the dv will get to the check of the target pvc name (and return error since it exists) before getting to the reconcileClone function which there you update the clone type annotation. Thats why if the tests wants to check for the event of "source busy" which requires the clone type annotation on the dv it should be done before creating the target pvc.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
I am not sure I understand the PR description, can you elaborate on this?

**Comment by ShellyKa13** [comment]
@brybacki the test is a negative test that creates the sourcepvc, create a pod to keep it busy, then creates the clone dv which can't do the clone yet since the source is busy. then it creates the targetpvc and expects eventually that the clone will fail since there already exists a pvc with the target name.
now the test after creating the target pvc checks for the clone type annotation on the dv. if the target pvc was created fast enough the dv will get to the check of the target pvc name (and return error since it exists) before getting to the reconcileClone function which there you update the clone type annotation. Thats why if the tests wants to check for the event of "source busy" which requires the clone type annotation on the dv it should be done before creating the target pvc.
I didnt want to go to that much details.. and if one will go over the test and read the commit msg I think that enough

**Pull request merged**
