### PR TITLE
Update vendor k8s dependencies to 1.13.4

### PR DESCRIPTION
**Pull request by cynepco3hahue**
**What this PR does / why we need it**:
Make possible to work with new client-go API and align versions with OKD repositories.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Update vendor k8s dependencies to 1.13.4
```

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
Should resolve also problems to move KubeVirt repo to 1.13.4.

**Comment by mhenriks** [comment]
Hi @cynepco3hahue I'd like include a couple other updates in this as well (controller run time and openapi generator).  Can you apply the following patch to the tree, run `make deps-update`, `make generate`, and push?

 ```diff
diff --git a/glide.yaml b/glide.yaml
index 410e8cd2..3027055b 100644
--- a/glide.yaml
+++ b/glide.yaml
@@ -33,7 +33,7 @@ import:
 - package: github.com/emicklei/go-restful-openapi
   version: ^1.0.0
 - package: sigs.k8s.io/controller-runtime
-  version: v0.1.9
+  version: v0.1.10
 - package: github.com/kelseyhightower/envconfig
   version: ^v1.3.0
 - package: github.com/openshift/api
diff --git a/hack/build/docker/builder/Dockerfile b/hack/build/docker/builder/Dockerfile
index 21ea9e19..f749f4f8 100644
--- a/hack/build/docker/builder/Dockerfile
+++ b/hack/build/docker/builder/Dockerfile
@@ -4,7 +4,7 @@ RUN dnf install -y qemu xz gzip git gradle gcc autoconf automake libtool python
 
 RUN pip3 install j2cli && pip3 install operator-courier
 
-ENV GIMME_GO_VERSION=1.11.5 GOPATH="/go" KUBEBUILDER_VERSION="1.0.7" ARCH="amd64"
+ENV GIMME_GO_VERSION=1.11.5 GOPATH="/go" KUBEBUILDER_VERSION="1.0.8" ARCH="amd64"
 
 RUN mkdir -p /gimme && curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | HOME=/gimme bash >> /etc/profile.d/gimme.sh
 
@@ -34,7 +34,7 @@ RUN \
     git checkout kubernetes-1.12.4 && \
     go install ./... ) && \
     ( cd $GOPATH/src/k8s.io/kube-openapi/cmd/openapi-gen && \
-    git checkout 0317810137be915b9cf888946c6e115c1bfac693 && \
+    git checkout a01b7d5d6c2258c80a4a10070f3dee9cd575d9c7 && \
     go install ./... ) && \
     (go get -u -d github.com/Masterminds/glide && \
      cd $GOPATH/src/github.com/Masterminds/glide && \
diff --git a/pkg/util/cert/triple/triple.go b/pkg/util/cert/triple/triple.go
index f1233501..6e8b2bc5 100644
--- a/pkg/util/cert/triple/triple.go
+++ b/pkg/util/cert/triple/triple.go
@@ -24,11 +24,13 @@ import (
 	certutil "k8s.io/client-go/util/cert"
 )
 
+// KeyPair contains a private key and certificate
 type KeyPair struct {
 	Key  *rsa.PrivateKey
 	Cert *x509.Certificate
 }
 
+// NewCA creates a new CA
 func NewCA(name string) (*KeyPair, error) {
 	key, err := certutil.NewPrivateKey()
 	if err != nil {
@@ -50,6 +52,7 @@ func NewCA(name string) (*KeyPair, error) {
 	}, nil
 }
 
+// NewServerKeyPair creates a new server key pair
 func NewServerKeyPair(ca *KeyPair, commonName, svcName, svcNamespace, dnsDomain string, ips, hostnames []string) (*KeyPair, error) {
 	key, err := certutil.NewPrivateKey()
 	if err != nil {
@@ -90,6 +93,7 @@ func NewServerKeyPair(ca *KeyPair, commonName, svcName, svcNamespace, dnsDomain
 	}, nil
 }
 
+// NewClientKeyPair creates a new client key pair
 func NewClientKeyPair(ca *KeyPair, commonName string, organizations []string) (*KeyPair, error) {
 	key, err := certutil.NewPrivateKey()
 	if err != nil {
```

**Comment by mhenriks** [comment]
@davidvossel the "triple" package was removed from client-go

**Comment by cynepco3hahue** [comment]
> So, what's going on with the vendored cert "triple" file. Is there no equivalent anymore that we can use from a vendored source? The pkg is very simple, so I don't necessarily have an issue pulling it out of the previous vendored directory into cdi's source, but i just want to make sure there's not a better option first.
> 
At least from what I saw, no, k8s guys removed it because it not used at all under k8s packages. I believe we can find some alternative to replace it with some existing go module, but for me, it will take some time, because I need to understand all private, public and CA stuff that we use and it also can be done after this PR merged to not delay dependencies update.

> other than handling of the "triple" pkg, everything else looks good to go from my perspective... as long as tests pass of course.

**Comment by cynepco3hahue** [comment]
> Hi @cynepco3hahue I'd like include a couple other updates in this as well (controller run time and openapi generator). Can you apply the following patch to the tree, run `make deps-update`, `make generate`, and push?
> 
> ```diff
> diff --git a/glide.yaml b/glide.yaml
> index 410e8cd2..3027055b 100644
> --- a/glide.yaml
> +++ b/glide.yaml
> @@ -33,7 +33,7 @@ import:
> - package: github.com/emicklei/go-restful-openapi
>   version: ^1.0.0
> - package: sigs.k8s.io/controller-runtime
> -  version: v0.1.9
> +  version: v0.1.10
> - package: github.com/kelseyhightower/envconfig
>   version: ^v1.3.0
> - package: github.com/openshift/api
> diff --git a/hack/build/docker/builder/Dockerfile b/hack/build/docker/builder/Dockerfile
> index 21ea9e19..f749f4f8 100644
> --- a/hack/build/docker/builder/Dockerfile
> +++ b/hack/build/docker/builder/Dockerfile
> @@ -4,7 +4,7 @@ RUN dnf install -y qemu xz gzip git gradle gcc autoconf automake libtool python
> 
> RUN pip3 install j2cli && pip3 install operator-courier
> 
> -ENV GIMME_GO_VERSION=1.11.5 GOPATH="/go" KUBEBUILDER_VERSION="1.0.7" ARCH="amd64"
> +ENV GIMME_GO_VERSION=1.11.5 GOPATH="/go" KUBEBUILDER_VERSION="1.0.8" ARCH="amd64"
> 
> RUN mkdir -p /gimme && curl -sL https://raw.githubusercontent.com/travis-ci/gimme/master/gimme | HOME=/gimme bash >> /etc/profile.d/gimme.sh
> 
> @@ -34,7 +34,7 @@ RUN \
>     git checkout kubernetes-1.12.4 && \
>     go install ./... ) && \
>     ( cd $GOPATH/src/k8s.io/kube-openapi/cmd/openapi-gen && \
> -    git checkout 0317810137be915b9cf888946c6e115c1bfac693 && \
> +    git checkout a01b7d5d6c2258c80a4a10070f3dee9cd575d9c7 && \
>     go install ./... ) && \
>     (go get -u -d github.com/Masterminds/glide && \
>      cd $GOPATH/src/github.com/Masterminds/glide && \
> diff --git a/pkg/util/cert/triple/triple.go b/pkg/util/cert/triple/triple.go
> index f1233501..6e8b2bc5 100644
> --- a/pkg/util/cert/triple/triple.go
> +++ b/pkg/util/cert/triple/triple.go
> @@ -24,11 +24,13 @@ import (
> 	certutil "k8s.io/client-go/util/cert"
> )
> 
> +// KeyPair contains a private key and certificate
> type KeyPair struct {
> 	Key  *rsa.PrivateKey
> 	Cert *x509.Certificate
> }
> 
> +// NewCA creates a new CA
> func NewCA(name string) (*KeyPair, error) {
> 	key, err := certutil.NewPrivateKey()
> 	if err != nil {
> @@ -50,6 +52,7 @@ func NewCA(name string) (*KeyPair, error) {
> 	}, nil
> }
> 
> +// NewServerKeyPair creates a new server key pair
> func NewServerKeyPair(ca *KeyPair, commonName, svcName, svcNamespace, dnsDomain string, ips, hostnames []string) (*KeyPair, error) {
> 	key, err := certutil.NewPrivateKey()
> 	if err != nil {
> @@ -90,6 +93,7 @@ func NewServerKeyPair(ca *KeyPair, commonName, svcName, svcNamespace, dnsDomain
> 	}, nil
> }
> 
> +// NewClientKeyPair creates a new client key pair
> func NewClientKeyPair(ca *KeyPair, commonName string, organizations []string) (*KeyPair, error) {
> 	key, err := certutil.NewPrivateKey()
> 	if err != nil {
> ```

@mhenriks Done

**Comment by cynepco3hahue** [comment]
@awels @mhenriks Hi guys CI is broken because of https://github.com/kubevirt/containerized-data-importer/pull/777/files#diff-9b26094ccd5d2b2fc40a6f4a94229aaaR302
The method definition `FileHostNs` does not exist at all under the repository.

**Comment by awels** [comment]
Yes sorry I merged something without rebasing it, and that is what broke, I will create a fix.

**Comment by awels** [comment]
@mhenriks CI is happy (besides one failure due it CI system not working right). You happy?

**Pull request merged**
