### PR TITLE
Use directly official libnbd go bindings

### PR DESCRIPTION
**Pull request by alicefr**
**What this PR does / why we need it**:
Currently, CDI relies for the libnbd bindings on [mrnold/go-libnbd](https://github.com/mrnold/go-libnbd). The major issue in using the official go bindings and bazel consists that gazelle doesn't support pkg-conf. Consequently, the link and cflags are not automatically generated together with the BUILD.bazel file. A possible workaround is to add the missing flags using buildozer. 

The support for cgo and pkg-config has been refused upstream (see https://github.com/bazelbuild/bazel-gazelle/pull/556). Hence, I don't think we can hope that it will be added in the future.
   

**Special notes for your reviewer**:
This PR manually adds the flags not generated by gazelle at the BUILD.bazel creation

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by alicefr** [comment]
hi @mrnold a review and feedback from your side will be very much appreciated :)

**Comment by alicefr** [comment]
Locally I can modify the BUILD.bazel file and the `make bazel-generate` works. In the CI it seems isn't generated. I need to understand why :/

**Comment by mrnold** [comment]
> hi @mrnold a review and feedback from your side will be very much appreciated :)

I 100% support removal of mrnold/go-libnbd by any means necessary. Thanks for taking on this work! This change looks good to me, but I don't know what else it needs to pass the tests.

**Comment by alicefr** [comment]
@mrnold many thanks!

Maybe they're due to some flakiness. I'll try to restart

/restart

**Comment by alicefr** [comment]
The tests are failing because the importer pod crashes with:
```bash
/usr/bin/cdi-importer: /lib64/libnbd.so.0: version `LIBNBD_1.6' not found (required by /usr/bin/cdi-importer)
```
Not sure why it isn't correctly linked. The library is present

**Comment by alicefr** [comment]
We need a more recent libnbd version:
```bash
$ k  exec -ti test-importer -- bash
ldd -r /usr/bin/cdi-importer 
/usr/bin/cdi-importer: /lib64/libnbd.so.0: version `LIBNBD_1.6' not found (required by /usr/bin/cdi-importer)
	linux-vdso.so.1 (0x00007ffe9b2d4000)
	libm.so.6 => /lib64/libm.so.6 (0x00007faa51f81000)
	libnbd.so.0 => /lib64/libnbd.so.0 (0x00007faa51f50000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007faa51f2e000)
	libc.so.6 => /lib64/libc.so.6 (0x00007faa51d63000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faa520cc000)
	libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007faa51b93000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007faa51a08000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007faa518d4000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007faa518b3000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007faa51730000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007faa51729000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007faa51712000)
	libnettle.so.8 => /lib64/libnettle.so.8 (0x00007faa516cf000)
	libhogweed.so.6 => /lib64/libhogweed.so.6 (0x00007faa5168a000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007faa515e5000)
	libz.so.1 => /lib64/libz.so.1 (0x00007faa515cb000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007faa5159f000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007faa51594000)
undefined symbol: nbd_set_strict_mode, version LIBNBD_1.6	(/usr/bin/cdi-importer)
undefined symbol: nbd_get_strict_mode, version LIBNBD_1.6	(/usr/bin/cdi-importer)
undefined symbol: nbd_opt_list_meta_context, version LIBNBD_1.6	(/usr/bin/cdi-importer)
undefined symbol: nbd_get_nr_meta_contexts, version LIBNBD_1.6	(/usr/bin/cdi-importer)
undefined symbol: nbd_get_meta_context, version LIBNBD_1.6	(/usr/bin/cdi-importer)
undefined symbol: nbd_clear_meta_contexts, version LIBNBD_1.6	(/usr/bin/cdi-importer)
undefined symbol: nbd_aio_opt_list_meta_context, version LIBNBD_1.6	(/usr/bin/cdi-importer)
$ rpm -aq libnbd
libnbd-1.4.1-2.fc33.1.x86_64
$ dnf remove libnbd && dnf install -y libnbd
$ rpm -aq libnbd
libnbd-1.6.5-1.fc33.x86_64
$ ldd -r /usr/bin/cdi-importer 
	linux-vdso.so.1 (0x00007ffde53d0000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ffb43a52000)
	libnbd.so.0 => /lib64/libnbd.so.0 (0x00007ffb43a1f000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ffb439fd000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ffb43832000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffb43b9d000)
	libgnutls.so.30 => /lib64/libgnutls.so.30 (0x00007ffb43662000)
	libxml2.so.2 => /lib64/libxml2.so.2 (0x00007ffb434d7000)
	libp11-kit.so.0 => /lib64/libp11-kit.so.0 (0x00007ffb433a3000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007ffb43382000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007ffb431ff000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ffb431f8000)
	libtasn1.so.6 => /lib64/libtasn1.so.6 (0x00007ffb431e1000)
	libnettle.so.8 => /lib64/libnettle.so.8 (0x00007ffb4319e000)
	libhogweed.so.6 => /lib64/libhogweed.so.6 (0x00007ffb43159000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007ffb430b4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007ffb4309a000)
	liblzma.so.5 => /lib64/liblzma.so.5 (0x00007ffb4306e000)
	libffi.so.6 => /lib64/libffi.so.6 (0x00007ffb43063000)

```

**Comment by awels** [comment]
@alicefr This ready for review?

**Comment by alicefr** [comment]
@awels from my side yes :) at least if we want to use buildozer to inject the cflags

**Comment by alicefr** [comment]
@mhenriks any feedback :)

**Comment by awels** [comment]
I am fine with that
/lgtm
Waiting for @mhenriks feedback before approving, but I am good with this.

**Pull request merged**
