### PR TITLE
[test] Import from registry using credentials - tier 1 test

### PR DESCRIPTION
**Pull request by tomob**
Signed-off-by: Tomasz Baranski <tbaransk@redhat.com>

**What this PR does / why we need it**:

This PR adds a tier1 test for importing an image from a repository that requires user credentials.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by tomob** [comment]
> I would also make both registries readonly as we are not pushing to them in any way.

`registry-populate` container does push images to the registries.

**Comment by awels** [comment]
Hmm I thought we just copied some files somewhere, so I guess we can keep one R/W while the other is read only.

**Pull request merged**
