### PR TITLE
Update the RFE ID used for CSI tests

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:
Update the RFE ID used for CSI tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by kgoldbla — COMMENTED** [review]
The rfe  CNV-4219 has been correctly added

**Comment by brybacki** [comment]
Maybe it was to slow to be deleted? Let's see if it repeats
```
                        Message: "All content successfully deleted, may be waiting on finalization",
```
/test pull-containerized-data-importer-e2e-k8s-1.19-ceph

**Comment by akalenyu** [comment]
> Maybe it was to slow to be deleted? Let's see if it repeats
> 
> ```
>                         Message: "All content successfully deleted, may be waiting on finalization",
> ```
> 
> /test pull-containerized-data-importer-e2e-k8s-1.19-ceph

We have seen it a few times before:
```
I believe one of our flakes (https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1905/pull-containerized-data-importer-e2e-k8s-1.19-ceph/1430164282548424704)

is related to https://github.com/kubernetes-csi/external-snapshotter/pull/360

I saw they tried to backport it to 2.1 (what we're using) but the PR was declined with:
https://github.com/kubernetes-csi/external-snapshotter/pull/534#issuecomment-893449553
```

We might want to try bumping the external snapshotter from 2.1

**Comment by brybacki** [comment]
@akalenyu very interesting find, 
yes, we definitely should bump the external snapshotter to a supported version (if there are no problems/conflicts with that)

**Pull request merged**
