### PR TITLE
Try to use the CDIConfig proxy URL if it is set, if not use port-forward

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
We always use port-forward in our upload tests, but port-forward fails often and does not recover. This PR attempts to use the proxy URL specified in the CDIConfig instead before attempting port-forward. If the cluster being tested on has a more stable proxy URL it will be used instead.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
Will we eventually have one configured by `make cluster-sync` so we can retire the `kubectl port-forward` code?

**Comment by awels** [comment]
Well the thought is eventually make cluster-up/sync will create a stable port like for the registry and some other services. And we can use that so we don't have to deal with the instability of kubectl port-forward

**Comment by brybacki** [comment]
And this can already work on systems when the URL is defined - like OCP
/lgtm

**Pull request merged**
