### PR TITLE
fix 'make cluster-up' hang

### PR DESCRIPTION
**Pull request by mhenriks**
I purged all my local docker images this morning.  After that, `make cluster-up` was hanging.  I believe this is an artifact of not having our kubernetes/openshift images in sync with each other since we use `gocli:latest` yet pin KUBERNETES_IMAGE/OPENSHIFT_IMAGE to specific sha.  Fix is to pin go cli and kubernetes/openshift images at hashes defined here [1].  Corresponding changes in kubevirtci [2] and kubevirt [3]

[1] https://github.com/kubevirt/kubevirtci/blob/master/README.md
[2] https://github.com/kubevirt/kubevirtci/pull/38
[3] https://github.com/kubevirt/kubevirt/pull/1464

### CODE REVIEW

**Comment by copejon** [comment]
I can't test this myself - @davidvossel can you PTAL / merge if it LGTY

**Comment by jeffvance** [comment]
needs rebase

**Comment by screeley44** [comment]
tested and lgtm

**Comment by davidvossel** [comment]
:+1: glad to see we're using a hash for the cli image now. I didn't catch that the first time.

**Pull request merged**
