### PR TITLE
minor fix to a manifest example

### PR DESCRIPTION
**Pull request by isueyoon**
**What this PR does / why we need it**:

It's a very tiny fix to an example yaml file, import-kubevirt-block-datavolume.yaml. Moved storageClassName key, value under the pvc. 

I copy and pasted this example to create a data volume, and noticed why it didn't work.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Why did you close this?

**Comment by isueyoon** [comment]
I thought I can reopen the issue after adding signoff, but I force pushed to my remote branch after amending the commit, so reopen wasn't allowed... I was debating to create another pull request, but it didn't look right to me. Sorry for my inexperience.

**Comment by awels** [comment]
No worries, feel free to open a new PR. And if you need to modify something don't close the PR, just keep pushing to your branch, and it should automatically update the PR.

**Comment by isueyoon** [comment]
Right right, for sure. Thank you so much!

**Pull request closed without merging**
