### PR TITLE
Update kubevirtci, 1.31 lanes

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump CI to test 1.31/1.30
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/hold
seeding the images fails much more with this change..

**Review by awels — APPROVED** [review]
/approve

**Comment by akalenyu** [comment]
/hold
/test pull-containerized-data-importer-e2e-ceph-wffc
super dodgy flake

**Pull request merged**
