### PR TITLE
Remove tar from the readers

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
This PR removes the ability to tar a kubevirt disk image, as that makes no sense since its a single file.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by mhenriks** [comment]
I understand that disk images are single files.  And tarring a single file doesn't make much sense.  But I thought that CDI was also supposed to be a more general purpose way to just put crap on a PVC?  If so, then I could imagine a tar reader being useful.

**Comment by awels** [comment]
Right, and it is still there for 'archive' content type, just not kubevirt content type.

**Comment by mhenriks** [comment]
@awels I must be confused.  Can you point we to where/how tar is handled for archive with http source?  Do we have a functional test for that?

**Comment by awels** [comment]
So tar works IF the following is true: contentType: archive, which will then send the data to tar for extraction. I am like and the test should be in transport_test.go. But I looked, and its not there. Let me add it there, since we really should be testing archive content type as well

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Pull request merged**
