### PR TITLE
Transport test - change struct of table tests

### PR DESCRIPTION
**Pull request by nellyc**
**What this PR does / why we need it**:
This PR just changes the struct of the transport table tests,
so instead of creating an it func (which is anyway to being reused),
i inserted it into the describe table
This allows us to properly fetch the test steps and test attirbutes

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
@nellyc It doesn't appear to compile the test properly, which is why the CI is failing.

**Comment by nellyc** [comment]
yeah, sorry for the noise, im on it

**Comment by awels** [comment]
before pushing code, you can run:
make test-unit to run the unit tests that travis runs.
make test-lint to run the linter that travis runs (looks like there is a problem here right now)
and after make cluster-up and make cluster-sync you can run make test-functional to run the STD CI tests to make sure everything works.

**Comment by awels** [comment]
@nellyc This still isn't compiling, just a heads up.

**Comment by nellyc** [comment]
> make cluster-up

@awels Thanks for the hints! 2 out of 3 already seem good, lets see if i can get the cluster up running for me :)

**Comment by j-griffith** [comment]
@nellyc are you still working this one?  Did you need some help?

**Comment by nellyc** [comment]
@j-griffith i was unable to get it running locally
will try again next week

**Comment by j-griffith** [comment]
@nellyc do you want some help with this or would you like to close it?  Let me know, happy to help out after a rebase if you like.

**Comment by aglitke** [comment]
@nellyc  Is this still relevant ?

**Pull request closed without merging**
