### PR TITLE
[release-v1.28] Preallocation global setting for 1.28

### PR DESCRIPTION
**Pull request by tomob**
**What this PR does / why we need it**:

This is a (manual) cherry-pick of #1565.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
/lgtm
(not that there's any value in another one :)

**Comment by awels** [comment]
Just an FYI, you can do a cherrypick of a PR into a branch by commenting /cherrypick <target branch> in a PR and it will attempt to cherrypick and make a PR for you. If that doesn't work, then do a manual. It saves a lot of work.

**Comment by tomob** [comment]
> Just an FYI, you can do a cherrypick of a PR into a branch by commenting /cherrypick in a PR and it will attempt to cherrypick and make a PR for you. If that doesn't work, then do a manual. It saves a lot of work.

Yes, I know, but in this case the bot broke commit comments, which broke sign-offs, which in turn broke dco approval. It was simplest to create the cherry-pick manually.

**Comment by tomob** [comment]
Can this be merged now?

**Pull request merged**
