### PR TITLE
Enable usestdlibvars linter

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**What this PR does / why we need it**:

This linter recommends using standard library variables rather than magic constants, so for example `201` is replaced with `http.StatusAccept`.

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ShellyKa13 — COMMENTED** [review]
/lgtm

**Comment by awels** [comment]
awesome love this one.
/lgtm
/approve
/retest-required

**Comment by akalenyu** [comment]
super chaotic failure in the istio lane with etcd being down, but I don't see how this PR would cause that
/test pull-containerized-data-importer-e2e-istio

**Pull request merged**
