### PR TITLE
[release-v1.49] Manual backport of 'Allow creating clones without source PVC (#2306)' 

### PR DESCRIPTION
**Pull request by alromeros**
**What this PR does / why we need it**: 

Manual backport of #2306 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
/lgtm
looks good, but I think you need to coordinate changes with @ShellyKa13, on this PR https://github.com/kubevirt/containerized-data-importer/pull/2406 I do not now which change should go first. Probably this one

**Comment by alromeros** [comment]
/hold

Holding since we have yet to reach a consensus on whether to backport this feature or not. The general idea seemed to be not doing it, which I'm not against, but I'll leave the PR open for some time just in case.

**Comment by alromeros** [comment]
Since https://github.com/kubevirt/containerized-data-importer/pull/2406 was merged, this backport is no longer necessary. I'm closing the PR.

**Pull request closed without merging**
