### PR TITLE
[release-v1.59] Catch up with non-logical main changes for ease of maintenance

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
Some of these backports can make stuff easier to maintain/backport later on

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/hold
further thoughts

**Comment by awels** [comment]
Discussed with some people and decided it will make our lives easier in the long run doing this.

**Pull request merged**
