### PR TITLE
Standardize setting go.mod to minor

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
This seems to be the standard, plus, if we don't do this we break the importing project's go.mod with our preferred specified patch version.
https://github.com/kubevirt/kubevirt/pull/12584/commits/73f66750d10bff34551404803d115469088a8ca7
Hitting an issue at https://github.com/kubevirt/kubevirt/pull/13152/files#r1824875505

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Standardize go.mod to not specify patch version
```

### CODE REVIEW

**Comment by akalenyu** [comment]
@Davo911 hey! am I breaking s390x with this PR? I don't expect that, since kubevirt does the same thing

**Comment by akalenyu** [comment]
We backed out due to a fluke in the get call, otherwise we would have seen more of these:
`INFO: Checking PVC phase: %s, resource version %s\n`

/test pull-containerized-data-importer-e2e-ceph

**Comment by Davo911** [comment]
> @Davo911 hey! am I breaking s390x with this PR? I don't expect that, since kubevirt does the same thing

Seems good on my side

**Pull request merged**
