### PR TITLE
Test framework dump service

### PR DESCRIPTION
**Pull request by brybacki**
**What this PR does / why we need it**:
Extend the test framework so it dumps service resources as a test artifact

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
I think maybe you pushed too much here, this includes all of the scratch space pvc code

**Comment by brybacki** [comment]
> I think maybe you pushed too much here, this includes all of the scratch space pvc code

Right, corrected.

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
