### PR TITLE
Build builder for arm64 and amd64, use Go 1.18.1

### LINKED ISSUE #2211: cdi-bazel-builder: exec user process caused "exec format error"
**What happened**:

When i build in aarch64 environment, i exec 'BUILD_ARCH=aarch64 make bazel-build' command, it occurs error:

+ docker run -v kubevirt-cdi-volume:/root:rw,z --security-opt label:disable --rm --entrypoint /entrypoint-bazel.sh quay.io/kubevirt/kubevirt-cdi-bazel-builder:0.0.13 mkdir -p /root/go/src/kubevirt.io/containerized-data-importer/_out
standard_init_linux.go:207: exec user process caused "exec format error"

I can't get quay.io/kubevirt/kubevirt-cdi-bazel-builder:0.0.13 image for aarch64, in addition,  When i exec './hack/build/bazel-build-builder.sh', it  can generate cdi-bazel-builder image for amd64, but not support aarch64

**What you expected to happen**:
I can build cdi in aarch64 environment

**How to reproduce it (as minimally and precisely as possible)**:
1. clone code
2. exec  'BUILD_ARCH=aarch64 make bazel-build'

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): v1.42.0
- Kubernetes version (use `kubectl version`): k3s version v1.22.7+k3s1 (8432d7f2)
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Kylin 4.0.2
- Kernel (e.g. `uname -a`): Linux 4.4.131-20200704.kylin.server-generic aarch64 
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by maya-r**
**What this PR does / why we need it**:
We want to sync up with the upcoming k8s 1.24, and that uses Go 1.18.
We want to build an arm64 builder as well (using buildah and qemu-user-static), so native `make cluster-sync` works on arm64.
Make a check for qemu-user-static on Linux, if it's not installed, the error is "exec format error" and it's hard to tell what is missing.

I have tested arm64 `make cluster-sync` with kind and only non-CDI images are problematic (fakeovirt, minio, quay.io/external_storage/local-volume-provisioner).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part 1 of 2 to fix #2211 (need to update the builder used before that issue can be closed)

**Special notes for your reviewer**:

**Release note**:

```release-note
Use Go 1.18.1 for the builder
Allow native builds on arm64
```

### CODE REVIEW

**Comment by mhenriks** [comment]
Let's see about not requiring buildah and qemu-user-static on the build machine.  Kubevirt does not have that requirement.  Maybe look here to see what they are ddoing?

https://github.com/kubevirt/kubevirt/blob/main/hack/builder/build.sh

**Comment by maya-r** [comment]
The way it works in kubevirt is that they rely on a container multiarch/qemu-user-static running privileged (so they can run a nested docker) and running the build in it.
I dislike avoiding dependencies with outside docker containers, but I went to list several reasons we might not want to use this particular container:
1. It only supports x86_64 as a host, so having it as a dependency would make it significantly difficult for people trying to build on new architectures.
2. It's on dockerhub, which we've been trying to avoid, but this is a solvable problem.
3. We are not building it in our repository, so anyone who has issues with it has to first look for the recipe, hope that it still works, etc., and it's a big maze. Due to point 1 this might become a problem fairly quickly.

**Comment by maya-r** [comment]
After experimenting a bit and being confused, it turns out SELinux is blocking multiarch/qemu-user-static from working.
The same seems to be true for kubevirt (when using docker, at least), I wonder if this is new to Fedora 35 or people have been building the builder with SELinux disabled.

**Comment by mhenriks** [comment]
> After experimenting a bit and being confused, it turns out SELinux is blocking multiarch/qemu-user-static from working.
The same seems to be true for kubevirt (when using docker, at least), I wonder if this is new to Fedora 35 or people have been building the builder with SELinux disabled.

If the container is being run privileged (as you suggest earlier) I'm surprised that SELinux is an issue

**Comment by maya-r** [comment]
Yeah, SELinux is an issue despite the container being privileged.

```
$ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
$ getenforce
Enforcing
$ docker run -it --platform linux/arm64 quay.io/centos/centos:stream9 sh
$ sudo setenforce 0
$ docker run -it --platform linux/arm64 quay.io/centos/centos:stream9 sh
sh-5.1# 
```

**Comment by mhenriks** [comment]
> Yeah, SELinux is an issue despite the container being privileged.
> 
> ```
> $ docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
> $ getenforce
> Enforcing
> $ docker run -it --platform linux/arm64 quay.io/centos/centos:stream9 sh
> $ sudo setenforce 0
> $ docker run -it --platform linux/arm64 quay.io/centos/centos:stream9 sh
> sh-5.1# 
> ```

Sorry, I'm not sure what this means.  Running a privileged does "turn off" selinux.  What is being denied by selinux?

**Comment by maya-r** [comment]
I am containing this change in #2279 which also includes more changes to make docker optional.
To avoid additional dependencies, it allows building for one architecture with docker if no buildah is installed.

**Comment by maya-r** [comment]
That one doesn't include the Go change, I guess... I'll do it separately.

**Pull request closed without merging**
