### PR TITLE
Add focus for destructive tests.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Sometimes destructive tests wouldn't clean up properly ruining the rest
of the run. This makes it so we can focus and skip the destructive
tests based on the lane settings. In combination with some changes to the
lanes we can speed up testing and have a separate lane for running destructive
tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
https://github.com/kubevirt/project-infra/pull/890 needs to be merged in order to test this properly.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
can we split the functional changes to tests/operator_test.go into a separate pull request? I don't understand the change given the commit message/pull request message

**Comment by awels** [comment]
The operator_test.go changes look big, but I really just wrapped the tests in a context, so we that --ginkgo.focus/skip can find the context name to focus/skip. But that is a lot of whitespace changes.

**Comment by brybacki** [comment]
:+1:

**Pull request merged**
