### PR TITLE
docs: Add docs for containerdisk labels

### LINKED ISSUE #3132: Create documentation explaining how PVC labels are derived from env vars on containerdisks
**Description**:

https://github.com/kubevirt/containerized-data-importer/pull/3103

Feature needs to be documented

### PR DESCRIPTION
**Pull request by 0xFelix**
**What this PR does / why we need it**:

Add docs which explain how PVCs of imported containerdisks can be decorated with additional labels.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3132

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by codingben — CHANGES_REQUESTED** [review]
Nice work Felix! I'd improve the syntax like I suggested.

**Comment by 0xFelix** [comment]
@codingben Addressed your comments.

**Review by codingben — APPROVED** [review]
/lgtm

**Pull request merged**
