### PR TITLE
k8s client upgrade to 1.16

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Update from 1.13.4 to 1.16.4.  Controller runtime updated as well.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

Currently referring to builder image in my docker hub, so hold until we do the dance required to update that thing in kubevirt org

**Release note**:

```release-note
Update k8s libraries to 1.16.4
```

### CODE REVIEW

**Comment by mhenriks** [comment]
/hold
currently references builder image in my dockerhub

**Comment by awels** [comment]
Looks good to me, except the builder piece.

**Comment by awels** [comment]
Bummer, looks like the OKD certificates are out of date and thus the cluster never comes up. This is fixed by a newer version of the image. Let me create a PR to address that.

**Pull request merged**
