### PR TITLE
Updated cluster-up with latest kubevirtci images.

### PR DESCRIPTION
**Pull request by awels**
Now using OKD 4.1.2 instead of 4.1.0.
k8s-1.13.3 and os-3.11.0-crio now using latest version of local volume provisioner:v2.3.2

Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Update images to contain latest local volume storage.
Update OKD to 4.1.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Comment by mhenriks** [comment]
@awels okd is not starting here because this branch is lacking the fix to ssh.sh in #872.  I suggest we merge that pr and rebase here.

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
Looks like the olm local storage installer was broken, I was using the 'latest' tag instead of stable and it wasn't creating the operator. This update should fix it.

**Comment by awels** [comment]
@mhenriks looks like the okd-4.1.2 got a green light one the last commit. Travis is still pending, I guess they are having an issue.

**Pull request merged**
