### PR TITLE
Change gid check to use ls instead of stat

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Change the gid check in functional tests to use ln -ln instead of stat, as stat might not be available in the container that we use for the verifier pod.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
"shell is bash" sounds like a harder requirement to satisfy than "stat is installed", but I assume you have a real case for wanting this change, and none of our tests seem to use non-bash shells yet, so
/lgtm

**Comment by awels** [comment]
Well out verifier pods are actually using the importer container. So as long as the importer container has bash it will work.

**Pull request merged**
