### PR TITLE
deprecation of local endpoint support

### PR DESCRIPTION
**Pull request by jeffvance**
Completes [338](https://github.com/kubevirt/containerized-data-importer/issues/338).

Removal of all code and tests related to local (file://) endpoints.

TODO: unit tests still are coded for local endpoints and need to be changed to use the new file server.

@aglitke @copejon @nellyc

### CODE REVIEW

**Comment by ovirt-infra** [comment]
Hello contributor, thanks for submitting a PR for this project! 

I am the bot who triggers "standard-CI" builds for this project.
As a security measure, I will not run automated tests on PRs that are not from white-listed contributors.

In order to allow automated tests to run, please ask one of the project maintainers to review the code and then do one of the following:

1. Type `ci test please` on this PR to trigger automated tests for it.
2. Type `ci add to whitelist` on this PR to trigger automated tests for it and also add you to the contributor white-list so that your future PRs will be tested automatically.
3. If you are planning to contribute to more than one project, maybe it's better to ask them to add you to the project organization, so you'll be able to run tests for all the organization's projects.

**Comment by jeffvance** [comment]
This pr depends on #429 afaict

**Comment by awels** [comment]
@jeffvance Doesn't look like it, this simply deprecates the file:/// and updates the unit tests to match (well maybe) and 429 is about the e2e tests.

**Comment by jeffvance** [comment]
agree with @awels  above

**Comment by jeffvance** [comment]
@davidvossel @awels @mhenriks Is there an http mock library that you find useful? I don't want to reinvent the wheel here. Thanks.

**Comment by awels** [comment]
@jeffvance I was looking at splitting up the NewDataStream into two sections, one section that parses and creates the transport stream (http/s3/etc) and one section that creates the other readers. That way in the unit test you can manually create a DataStream, setup file stream as the transport, and then call the part that sets up the other readers.

Looking at the unit test code that is partially there. That way we don't 'support' file streams, but it is not impossible to use them for testing purposes.

**Comment by awels** [comment]
Having worked on this a while, not sure my approach will work. I did find out golang has a net/http/httptest server build in, so we could use that.

**Comment by awels** [comment]
@jeffvance I was trying something like this:
```go
ts := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    w.WriteHeader(http.StatusOK)
    f, err := os.Open(fileName)
    if err != nil {
        w.WriteHeader(http.StatusNotFound)
        return
    }
    defer f.Close()
    n, err := io.copy(w, f)
    if err != nil {
        w.WriteHeader(http.StatusNotFound)
    }
}))
```
But it doesn't seem to work, I keep ending up with a deadlock.

**Comment by jeffvance** [comment]
@awels interesting. Thanks for trying. I'll keep working on it and I appreciate your time spent on this!

**Comment by jeffvance** [comment]
@awels I suspect the `defer f.Close()` above. Don't we want to keep the file open until after the `io.Copy`?

**Comment by awels** [comment]
@jeffvance Isn't the whole point of the defer that it doesn't get executed until the end of the code block, in this case the end of the function?

**Comment by jeffvance** [comment]
> Isn't the whole point of the defer that it doesn't get executed until the end of the code block

Yes. My thinking was that we didn't want to close the file before we read from it, ie a copy operation. But, most of the unit tests don't actually read the endpoint's content...

**Comment by awels** [comment]
@jeffvance my deadlock issue was that a lot of those tests expect file:// behavior and weren't reading the data since it works fine with a file://, however the http server is blocking waiting for data to be read from the stream, which a lot of the tests aren't doing. After I do a ds.Read(buf) it works a lot better.

**Comment by jeffvance** [comment]
> ...a lot of those tests expect file:// behavior ...

Yes! This pr is a bit more complicated than I originally expected but I'm still making progress to address the many tests they rely on :file// endpoints.

**Comment by awels** [comment]
I am actually also working on this, so if you want, you can stop

**Comment by jeffvance** [comment]
But this pr is to deprecate the code for local endpoints. Why do we want/need an additional pr. This is almost working...

**Comment by awels** [comment]
I wasn't going to make an additional PR, I will be using this one, with some updates.

**Comment by jeffvance** [comment]
my 6th commit is for @awels since I did not know he was creating his own pr based on this one. I haven't pushed my local changes in a couple of days and now that I know this pr is being used by someone else, it's time for a refresh...

**Comment by jeffvance** [comment]
replaced by #460

**Pull request closed without merging**
