### PR TITLE
Add node annotation on PVS for HPP only in Immediate Binding Mode

### PR DESCRIPTION
**Pull request by rollandf**
Signed-off-by: Fred Rolland <frolland@redhat.com>
Signed-off-by: Daniel Erez <derez@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by danielerez** [comment]
> I would just remove the code that explicity sets nodes, once the hpp (looking at that) is updated, then we don't need explicit binding at all.

We still want to support the old behaviour, so we need to keep the 'provisionOnNode' annotation handling.

**Comment by awels** [comment]
I think we can abandon this PR. The latest hostpath provisioner, supports the annotation in both volumeBindingModes. So there is no need to check for Immediate.

**Comment by rollandf** [comment]
Closing as HPP supports the annotation on both modes (waitforfirstcustomre/immediate)

**Pull request closed without merging**
