### PR TITLE
[release-v1.43] Manual backport of 2149 - alert summary

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

**What this PR does / why we need it**:
Manual backport of #2149 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
/hold
need to see if we require a bug for this

**Review by awels — APPROVED** [review]

**Comment by brybacki** [comment]
Test `[test_id:3944]succeed warm import from ImageIO to block volume` failed on lane pull-containerized-data-importer-e2e-k8s-1.21-ceph 
```
"message": "Unable to attach or mount volumes: unmounted volumes=[cdi-scratch-vol], unattached volumes=[kube-api-access-hh6df cdi-data-vol cdi-scratch-vol cdi-cert-vol]: error processing PVC cdi-e2e-tests-dv-func-test-48s2c/dv-imageio-warm-import-test-scratch: PVC is being deleted",
```
I remember there were fixes for something similar. Is it possible that fixes were not backported to this release branch? Or maybe that is a different failure.

**Pull request merged**
