### PR TITLE
Add cron-job sa to scc

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Add cronjob-sa to SCC so we can run inside Open Shift without issues.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
Can someone confirm that this actually works on OpenShift before I approve?  Should be able to simply edit the SCC with current virsion?

**Comment by akalenyu** [comment]
> Can someone confirm that this actually works on OpenShift before I approve? Should be able to simply edit the SCC with current virsion?

Yeah seems to do the trick. I added it and everything kicked off resulting in the DataImportCron's reaching
```
      status: "True"
      type: UpToDate
```

**Comment by mhenriks** [comment]
thanks @akalenyu!

**Comment by akalenyu** [comment]
> We have to handle upgrade case. Currently users are only added to the SCC when created.

Do you mean we have to make the change in https://github.com/kubevirt/containerized-data-importer/blob/3b91645515e8a17c2db2f6051b394a0890133c15/pkg/operator/controller/scc.go#L41 instead?

**Comment by awels** [comment]
Added code to ensure we add the cron user on upgrade as well.

**Pull request merged**
