### PR TITLE
Don't run raw images through qemu-img as it sometimes has issues tran…

### PR DESCRIPTION
**Pull request by awels**
…sferring files.

Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
qemu-img sometimes has issues transferring data, don't call qemu-img if we are transferring a raw file.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Don't call QEMU-IMG on transferring a raw disk image.
```

### CODE REVIEW

**Comment by mhenriks** [comment]
Will this cause scratch space to be used for importing raw images?

What do we know about the "issues" seen with qemu-img?  Would it be better to look into updating qemu-img?  I know we had an issue with a more recent version.  But maybe it's fixed?

**Comment by awels** [comment]
> Will this cause scratch space to be used for importing raw images?
> 
> What do we know about the "issues" seen with qemu-img? Would it be better to look into updating qemu-img? I know we had an issue with a more recent version. But maybe it's fixed?

No, this will stream a RAW image directly to the target file or block device. No scratch space and no qemu-img

**Comment by awels** [comment]
Oh and as an added bonus it will now also work with http sources that don't support range.

**Pull request merged**
