### PR TITLE
tests: correct check for containerdisk env vars eventually appearing

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
I believe this was the original intention, currently, we don't refresh the PVC from the API server.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
/lgtm
Feel free to put approve on there.

**Comment by 0xFelix** [comment]
Oops, thanks for fixing it.

**Pull request merged**
