### PR TITLE
Fix inverted logic - wait for the pod to stop existing.

### PR DESCRIPTION
**Pull request by maya-r**
**What this PR does / why we need it**:
This is part of #1603 split into its own change.
I would like to have this as its own change so we can backport it right away, whereas #1603 is something we'd like to test to see if it's stable for a while.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Comment by maya-r** [comment]
flake already reported in #1596
/test pull-containerized-data-importer-e2e-k8s-1.18-hpp-destructive

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.17-ceph
upload test that failed with:
io: read/write on closed pipe
seems kinda new.

**Comment by maya-r** [comment]
/cherry-pick release-v1.28

the "write on closed pipe" is because if the pipe writer in formRequestFunc encounters an error, it fails the test, so we can't retry.
(after some experimentation...) the only solution I can offer for it is to not report errors, since the goroutine blocks for a while.
I think it's better to pursue "don't rely on kubectl port-forward" than offer this patch...

**Pull request merged**
