### PR TITLE
Make deps update and bump to go 1.19 utilizing new builder

### LINKED ISSUE #2506: go 1.18.8 throwing medium security vulnerability
**What happened**:
go 1.18.8 is throwing a medium vulnerability with HTTP. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Running a vulnerability scan

**Additional context**:
This seems to be fixed in go 1.18.9

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`): 1.55.2
- Kubernetes version (use `kubectl version`): 1.21
- DV specification: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2506 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Might be nice if we also update the golang version at the same time? Already have a builder with 1.19.5

**Comment by awels** [comment]
Also pointing to the new builder (we created the builder, but are not using it yet) and if you want update the k8s libraries but that is not needed to update the golang version (we do need the new golang version to update the k8s libraries)

**Comment by akalenyu** [comment]
> Also pointing to the new builder (we created the builder, but are not using it yet) and if you want update the k8s libraries but that is not needed to update the golang version (we do need the new golang version to update the k8s libraries)

I think we need to bump bazel version as well for go 1.19
https://github.com/bazelbuild/rules_go/pull/3231
https://github.com/kubevirt/kubevirt/commit/9e15eca23c8554a13f19cd71ff8f82052d73c35a

otherwise rpm-deps yells at me ```2023/03/09 13:37:32 link: unlinkable object (from package golang.org/x/sys/unix) - compiler requires -p flag```

**Comment by awels** [comment]
Okay, I just want us to use go 1.19 for the next release.

**Comment by awels** [comment]
Oh so we need a new bazel builder then?

**Comment by awels** [comment]
Okay, then I guess we need to make a new bazel builder

**Comment by akalenyu** [comment]
> Okay, then I guess we need to make a new bazel builder

Yep, don't think it block this PR though

**Pull request merged**
