### PR TITLE
Upgrade golangci-lint to v1.54.2 and fix findings

### PR DESCRIPTION
**Pull request by nunnatsa**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by nunnatsa** [comment]
I think golangci-lint v1.54.2 requires golang v1.20+ 

@awels - do you plan to upgrade in the near future?

**Comment by awels** [comment]
I just added #2875 which updates the builder to 1.20.7, once that is merged and the new builder is available, I will update the rest to use golang 1.20.7

**Pull request merged**
