### PR TITLE
Backport #875 and #869 to 1.9

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Backport #875 and #869 to 1.9 branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by mhenriks** [comment]
All test failures related to there being multiple `cdi-deployment` pods.  Weird.  The leader election test must be causing this somehow.

**Comment by mhenriks** [comment]
ci test please

**Comment by awels** [comment]
Well the leader election tests (the new ones at least) should not be in 1.9 branch.

**Comment by awels** [comment]
Oh this branch probably doesn't have the fix where we changed the prefix of the second pod in case it took too long for the pod to die.

**Comment by mhenriks** [comment]
Added #840 to this

**Comment by awels** [comment]
lgtm, failures are the usual we get permission denied when cleaning up sometimes.

**Comment by mhenriks** [comment]
ci test please

**Pull request merged**
