### PR TITLE
make tools support aarch64

### PR DESCRIPTION
**Pull request by zhlhahaha**
**What this PR does / why we need it**:
tools images are necessary for e2e tests, add support for aarch64

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by zhlhahaha** [comment]
cc: @awels

**Comment by zhlhahaha** [comment]
Hi Alexander, I am doing e2e tests of CDI on arm64, but get some errors. I am still investigating these tests.

**Comment by awels** [comment]
Hi, thanks for the PR, looks good to me. We can ignore that one failure, I am working on figuring out why it is so flaky.
/lgtm
/approve

**Comment by awels** [comment]
/override pull-containerized-data-importer-e2e-k8s-1.20-hpp-istio

**Pull request merged**
