### PR TITLE
Correct check in badserver_tests

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:
Adds a missing check at the end of the tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.17-hpp

````
  Unexpected error:
      <*errors.errorString | 0xc000704000>: {
          s: "Unexpected return value 502 expected 200, Response: {}",
      }
      Unexpected return value 502 expected 200, Response: {}
  occurred
````

log from cdi-uploadproxy says:
````
I0625 15:57:01.760254       1 uploadproxy.go:192] Received valid token: pvc: import-long-name-dv.123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-123456789-1234567890, namespace: cdi-e2e-tests-upload-func-test-nlzg9
2020/06/25 15:59:15 http: proxy error: dial tcp 10.104.132.60:443: connect: connection timed out
````

Not sure why it would time out. Cluster network really slow?

**Comment by awels** [comment]
Yeah, we have a ton of tests running right now and the system is highly loaded, I am seeing a lot of 502s like that on many PRs

**Comment by brybacki** [comment]
Probably the badserver/flaky test needs longer timeout now, when it actually checks the status:
```
                "name": "badserver-dv",
                "phase": "ImportInProgress",

                 "message": "Back-off 2m40s restarting failed container=importer pod=importer-badserver-dv_cdi-e2e-tests-badserver-func-test-wpddl(86e1f18a-b70a-11ea-b933-525500d15501)"
```

**Comment by brybacki** [comment]
as for second fail: 
`[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component] Upload tests [test_id:3997] Upload image to data volume - kill container and verify retry count `
- there are no logs left from this run
- the container was actually killed (but not gracefully) so maybe we can just catch exit code 137 and treat It as a good execution?

**Comment by maya-r** [comment]
DataVolume badserver-dv not in phase Succeeded within 8m20s

Wow, that's quite a time limit to hit.

**Comment by brybacki** [comment]
something is bad in crio lane:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1262/pull-containerized-data-importer-e2e-os-3.11.0-crio/1277523354466652160/artifacts/pods/1_cdi-em1ie_cdi-bad-webserver-865f9f87b4-2fjdx-http.log

**Comment by brybacki** [comment]
looks like this does not work, but why?
```
	counterBuf, err := ioutil.ReadFile("state")
```

**Comment by brybacki** [comment]
Just checking if the problem is persitent or temporary:
/test pull-containerized-data-importer-e2e-os-3.11.0-crio

**Comment by brybacki** [comment]
the fail here looks like file integrity problem, a known case,

/test pull-containerized-data-importer-e2e-os-3.11.0-crio

**Comment by brybacki** [comment]
@maya-r @awels 
What is our plan regarding this change. I think it is good enough to be merged. But if there are any concerns that it is not robust enough (see discussions on PR #1278 ), then we might need to spend more time on improving the implementation.

**Pull request merged**
