### PR TITLE
Add library function to determine if a PVC is waiting for first consu…

### PR DESCRIPTION
**Pull request by brybacki**
**What this PR does / why we need it**:

Add library function to determine if a PVC is waiting for first consumer before binding (and before it can be populated).

IsWaitForFirstConsumerBeforePopulating indicates if the persistent volume passed in is in ClaimPending state and waiting for first consumer. It follows the logic:
1. If the PVC is not owned by a DataVolume, return false, we can not assume it will be populated
2. If the PVC is owned by a DataVolume, look up the DV and check the phase, if phase WaitForFirstConsumer return true
3. If the PVC is owned by a DataVolume, look up the DV and check the phase, if phase !WaitForFirstConsumer return false

This is needed so the users of CDI (kubevirt) can detect and correctly handle PVC's in this state. See https://github.com/kubevirt/kubevirt/pull/4025

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
A new library function IsWaitForFirstConsumerBeforePopulating  
```

### CODE REVIEW

**Comment by awels** [comment]
looks good, but I would like some unit tests. Similar to these: https://github.com/kubevirt/containerized-data-importer/pull/1400/files#diff-b467b5dba3091841c7ee7bdcd589408217fa09bdef49ea0ab9cef01dbb07b197R557-R618

**Comment by brybacki** [comment]
> looks good, but I would like some unit tests. Similar to these: https://github.com/kubevirt/containerized-data-importer/pull/1400/files#diff-b467b5dba3091841c7ee7bdcd589408217fa09bdef49ea0ab9cef01dbb07b197R557-R618

I have added simple unit test, but I wonder if this is the good place. Do we have anything against adding tests to api packages, or is it not there because so far API did not have any logic. I can move this test there to API. 

Anyway now we have some duplication in APIs. It is the same util in just two places so maybe it is not yet worth adding 'commons' but it will make tests duplicated also.

**Comment by awels** [comment]
So the problem is that v1alpha1 DVs != v1beta1 DVs, so you can't write one unit test to exercise both functions. The duplication kills me as well, but I see no alternative.

**Comment by awels** [comment]
Looks like the unit tests are failing?

**Comment by brybacki** [comment]
> Looks like the unit tests are failing?

I did push the wip by mistake, now fixed.

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
