### PR TITLE
[WIP] Provide a jinja2 template for the cdi manifest 

### PR DESCRIPTION
**Pull request by shiywang**
Fixes https://github.com/kubevirt/containerized-data-importer/issues/223

### CODE REVIEW

**Comment by shiywang** [comment]
@jeffvance @copejon PTAL

**Comment by copejon** [comment]
I've pulled down and run `make manifests`.  LGTM

**Comment by aglitke** [comment]
Does this close #323

**Comment by jeffvance** [comment]
@aglitke Yes I think it does. I'll update the description and close issue 323.

**Pull request merged**
