### PR TITLE
Fix test failure - missing pod following recreate of CDI

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:
From some debugging, it looks like the priority class tests don't properly wait for
redeploy to finish and thus the following tests get an initial wrong slice of cdiPods
(Consider 2 cdi-uploadproxy pods, one of which is terminating, making way to the new one)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Okay, I guess we need to make sure those are cleaned up before moving to the next test then

**Comment by akalenyu** [comment]
> Okay, I guess we need to make sure those are cleaned up before moving to the next test then

Yeah just have to find a nice way that relies on the deployment status

**Comment by akalenyu** [comment]
> > Okay, I guess we need to make sure those are cleaned up before moving to the next test then
> 
> Yeah just have to find a nice way that relies on the deployment status

Should be ok now

**Review by ShellyKa13 — COMMENTED** [review]
/lgtm

**Pull request merged**
