### PR TITLE
[release-v1.49]  Cherry pick #2351

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Manual cherry-pick of #2351

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
just a heads up that if we merge this it'll end up an openshift release, might be what we want though

**Comment by mhenriks** [comment]
> just a heads up that if we merge this it'll end up an openshift release, might be what we want though

that is the whole idea

**Comment by akalenyu** [comment]
> > just a heads up that if we merge this it'll end up an openshift release, might be what we want though
> 
> that is the whole idea

hmm might want to hold until release though so it won't slip?

**Pull request closed without merging**
