### PR TITLE
dataStream: DataStreamOptions - comment on base64

### PR DESCRIPTION
**Pull request by danielerez**
Signed-off-by: Daniel Erez <derez@redhat.com>

**What this PR does / why we need it**:
dataStream -> DataStreamOptions -> SecKey: comment that the string is encoded in base64.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
The rebase should fix the CI failures.

**Comment by danielerez** [comment]
ci test please

**Comment by danielerez** [comment]
ci please test

**Comment by danielerez** [comment]
ci test please

**Pull request merged**
