### PR TITLE
[release-v1.18] backport "replace gzip with snappy" for network clone and #1426

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

backport #1419 #1426 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Use Snappy compression for network cloning
```

### CODE REVIEW

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Comment by awels** [comment]
Hmmm looks like the lanes are broken as they are trying to use betav1 api, which doesn't exist in this release.

**Comment by mhenriks** [comment]
@awels problem is that it is attempting to upgrade from 1.24.1
```
++ curl -s https://github.com/kubevirt/containerized-data-importer/releases/latest
++ grep -o 'v[0-9]\.[0-9]*\.[0-9]*'
+ export UPGRADE_FROM=v1.24.1
+ UPGRADE_FROM=v1.24.1
+ echo 'Upgrading from verions: v1.24.1'
Upgrading from verions: v1.24.1
```

**Comment by awels** [comment]
Yeah, that is not a good thing... I guess we need to fix project-infra to set UPGRADE_FROM to 1.18. Let me work on that.

**Comment by awels** [comment]
or that, I am fine with that
/lgtm

**Pull request merged**
