### PR TITLE
Conform with top level kubevirt github project

### PR DESCRIPTION
**Pull request by davidvossel**
## Changes
* pkg path has changed from github.com/kubevirt/containerized-data-importer to **kubevirt.io/containerized-data-importer**
* The cdi.io group and annotation prefix is now called **cdi.kubevirt.io**

## Rational

While CDI is not coupled to kubevirt, it is currently under the kubevirt organization. It's feasible that someone will consume the CDI project outside of KubeVirt and that doesn't necessarily mean the project can't be developed under the kubevirt organization.

The github.com/kubevirt/containerized-data-importer to **kubevirt.io/containerized-data-importer** package path change follows the pattern we've already set for KubeVirt packages. CDI is going to be consumed soon by other projects (starting with kubevirt shortly), so we'll want the package directory to be consistent. 

The cdi.io to **cdi.kubevirt.io** group version change is also reflective of cdi being in the kubevirt organization. We don't currently own cdi.io, however we can easily create a cdi.kubevirt.io landing page if we'd like for the cdi project. 

## Dev Flow Updates.
everyone working on cdi must make this change to their local dev host.

```
mkdir -p $GOPATH/kubevirt.io
mv $GOPATH/github.com/kubevirt/containerized-data-importer $GOPATH/kubevirt.io/containerized-data-importer
```

### CODE REVIEW

**Comment by davidvossel** [comment]
@rmohr @fabiand 

It would be nice to have your eyes on this one. Do you all agree with this change?

**Comment by rmohr** [comment]
@davidvossel looks good. You may also want to do something like done in https://github.com/kubevirt/kubevirt.github.io/pull/38. Now that we finally have working tls and the right urls it may as well make sense if we make `go get -d kubevirt.io/cdi` work too.

**Comment by jeffvance** [comment]
@davidvossel **only** 38 files changed, this is small! :-)
Can you look at merged pr #194 and let me know if I should change the cdi labels to _cdi.kubevirt.io.zzz_
Thanks

**Comment by davidvossel** [comment]
> Can you look at merged pr #194 and let me know if I should change the cdi labels to cdi.kubevirt.io.zzz
Thanks

This patch already addresses that :)  anything that was cdi.io is now cdi.kubevirt.io, including the labels.

**Comment by jeffvance** [comment]
@davidvossel I'm referring above to the labels defined in _pkg/common/common.go_. I don't see that file in your patch.

**Comment by davidvossel** [comment]
related to #203 

Note that we're going to want to make a decision about this PR before CDI's next release. There are some workflows that utilize the CDI annotations which got changed recently.  This patch changes those annotations yet again. We'll want to stabilize those annotations before the release.

Ideally these workflows begin using the well defined DataVolume API soon.

**Comment by shiywang** [comment]
@davidvossel once this merged, does that mean we could plan to implement a stagging mechanism like I described here: https://github.com/kubevirt/kubevirt-ansible/issues/284#issuecomment-397136400 ?

I mean currently it will only do the job we don't have to bump the manifests from [here](https://github.com/kubevirt/containerized-data-importer/blob/master/manifests/controller/cdi-controller-deployment.yaml) to [here](https://github.com/kubevirt/kubevirt-ansible/blob/master/roles/cdi/templates/cdi-controller-deployment.yml).

**Comment by copejon** [comment]
Added DNM tag for the time being until we've got the annotations and versions sorted out

**Comment by davidvossel** [comment]
@copejon @jeffvance Due to all the recent confusion, I have removed touching the annotations at all in this patch. This patch doesn't modify any behavior other than changing the name of the DataVolume's groupVersion and the CDI pkg paths. 

Also, when we're ready for this patch to go in, I need someone to change the travis configuration for CDI install the repo at $GOPATH/src/kubevirt.io/containerized-data-importer rather than the current $GOPATH/src/github.com/kubevirt/containerized-data-importer.

I can't express that kind of change in .travis.yml. Someone who has access to the travis settings for this project will need to do that.

**Comment by rmohr** [comment]
Regarding to Travis, can't you just add `go_import_path`: https://docs.travis-ci.com/user/languages/go/#Go-Import-Path?

**Comment by davidvossel** [comment]
> Regarding to Travis, can't you just add go_import_path: https://docs.travis-ci.com/user/languages/go/#Go-Import-Path?

@rmohr whelp... you're right. that worked, thanks!

nevermind @copejon and @jeffvance. Travis works now :)

**Comment by jeffvance** [comment]
@davidvossel We spent most of today defining the process and tooling for real cdi releases. We 
reverted 2 prs which broke code that consumed cdi images and/or manifests. After that we fixed make so that downstream rpm creation works w/o docker present. We created prs which define the final (we hope) pvc annotations and the first real cdi version, v1.0.0. 
Now that your pr does not change pvc annotations I think we can merge it but that will have to wait till tomorrow.

**Comment by jeffvance** [comment]
@davidvossel please rebase.

**Comment by davidvossel** [comment]
rebased

**Comment by davidvossel** [comment]
Hey, @jeffvance @copejon can we merge now? There's a dependent PR in KubeVirt that will need this in the next few days.

**Comment by jeffvance** [comment]
@davidvossel ack. Jon is on pto. I'm deep into the introspection code and don't want to disturb my env, but I also do want this pr blocking anyone. I'll try to get it merged today.

**Comment by davidvossel** [comment]
@jeffvance @screeley44 

The unit tests are correct. The import paths in the tests needed to be updated to reflect the changes in this PR. 

I pushed the fix. Travis should pass now.

**Comment by jeffvance** [comment]
lgtm

**Pull request merged**
