### PR TITLE
Import pvc 'cdi.kubevirt.io/storage.pod.phase' annotation valu…

### LINKED ISSUE #494: Import pvc 'cdi.kubevirt.io/storage.pod.phase' annotation value is wrong when import fails
BUG REPORT

kind bug

**What happened**:
VM disk image import fails and 'cdi.kubevirt.io/storage.pod.phase' annotation in PVC has the value of 'Runing'

**What you expected to happen**:
The annotation should indicate importing failed. I think this happnes as a result of the new retryOnFailure mechanism that was introduced lately, but I'm not sure.
The reason is that kubernetes consider the pod as 'running' (pod's status) as long as the pod retries to load.

**How to reproduce it (as minimally and precisely as possible)**:
change the endpoint url in the datavolume.yaml to invalid url.
deploy import datavolume.yaml
import pod fails. Pod's status is CrashLoopBackOff but it's phase is still 'running' (get pod -o yaml)

**Anything else we need to know?**:
I believe the cloner will have the same issue.

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by zvikorn**
…e is wrong when import fails. Issue #494

Signed-off-by: tavni <tavni@redhat.com>

**What this PR does / why we need it**:
Fix for Issue #494 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #494 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
So basically the pod status was not matching the container status in the case of failure of the container. In that case I agree and lgtm.

**Comment by j-griffith** [comment]
Thanks @zvikorn , LGTM.  I'll rebase and merge

**Comment by zvikorn** [comment]
ci test please

**Comment by j-griffith** [comment]
ci test please

**Comment by zvikorn** [comment]
ci test please

**Comment by j-griffith** [comment]
ci test please

**Comment by j-griffith** [comment]
ci test please

**Comment by j-griffith** [comment]
ci test please

**Comment by zvikorn** [comment]
ci test please

**Pull request merged**
