### PR TITLE
Add init containers log to artifacts

### PR DESCRIPTION
**Pull request by akalenyu**
Signed-off-by: Alex Kalenyuk <akalenyu@redhat.com>

**What this PR does / why we need it**:
Start collecting init container logs as well.
Doing this as an attempt to debug a flake with self signed certs and our registry host test deployment.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
Looks like querying init container logs with `SinceTime: &logStart` won't work (logs stopped slightly after `make cluster-sync`).
Trying to drop `SinceTime`.

**Comment by brybacki** [comment]
looks like it works, now there are init container logs here:
https://gcsweb.ci.kubevirt.io/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1970/pull-containerized-data-importer-e2e-k8s-1.20-hpp/1445285932885348352/artifacts/pods/

**Pull request closed without merging**
