### PR TITLE
Enable tests for featuregates

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:
Adds missing feature-gates_suite_test. Now tests for featuregates can actually be run. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
A little bit off-topic, regarding the: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1600/pull-containerized-data-importer-e2e-k8s-1.17-hpp/1352653678355419136 fail 

Cloner Test Suite [test_id:4953]Should clone imported data within same namespace and preserve fsGroup expand_more

Isn't it something that was supposed to be fixed?

**Comment by maya-r** [comment]
yeah it looks like the verifier ran before the clone. I have a change to wait for the targetDV to be successful instead of bound

**Pull request merged**
