### PR TITLE
Fix uploadproxy override in cluster-sync

### PR DESCRIPTION
**Pull request by EduardGomezEscandell**
**What this PR does / why we need it**:
Attempting to use virtctl on this repository's cluster fails:
```
edu@fedora:~/containerized-data-importer$ virtctl image-upload dv hello-example --size=1Gi --image-path cirros-0.6.2-x86_64-disk.img --force-bind
Using existing PVC default/hello-example
the server could not find the requested resource
parse "127.0.0.1:32768": first path segment in URL cannot contain colon
```

This is because the upload proxy override is missing the https prefix:
```
edu@fedora:~/containerized-data-importer$ k describe cdiconfig | grep 'Upload Proxy'
  Upload Proxy URL Override:  127.0.0.1:32814
  Upload Proxy URL:             127.0.0.1:32814
```

After this fix:
```
edu@fedora:~/containerized-data-importer$ k describe cdiconfig | grep 'Upload Proxy'
  Upload Proxy URL Override:  https://127.0.0.1:32814
  Upload Proxy URL:             https://127.0.0.1:32814
```

And image-upload now works:
```
edu@fedora:~/containerized-data-importer$ virtctl image-upload dv hello-example --size=1Gi --image-path cirros-0.6.2-x86_64-disk.img --force-bind --insecure
PVC default/hello-example not found 
DataVolume default/hello-example created
Waiting for PVC hello-example upload pod to be ready...
Pod now ready
Uploading data to https://127.0.0.1:32814

 20.44 MiB / 20.44 MiB [==================================================================================================================================] 100.00% 0s

Uploading data completed successfully, waiting for processing to complete, you can hit ctrl-c without interrupting the progress
Processing completed successfully
Uploading cirros-0.6.2-x86_64-disk.img completed successfully
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Check out the same code in Kubevirt:

https://github.com/kubevirt/kubevirt/blob/main/hack/cluster-deploy.sh#L53-L56

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by EduardGomezEscandell** [comment]
To exercise this code you can run the following script, all you need is some VM image:

```bash
IMAGE=./cirros-0.6.2-x86_64-disk.img

# Start cluster
make cluster-up
make cluster-sync

# Patch cluster (Solved in https://github.com/kubevirt/containerized-data-importer/pull/3306)
host_port=$(./cluster-up/cli.sh ports uploadproxy | xargs)
override="https://127.0.0.1:$host_port"
kubectl patch cdi cdi --type merge -p '{"spec": {"config": {"uploadProxyURLOverride": "'"$override"'"}}}'

# Break the uploadproxy
cat << EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata: 
  name: default-deny-ingress
spec: 
  podSelector: {}
  policyTypes: 
  - Ingress
EOF

# Exercise the error
virtctl image-upload dv hello-example --size=1Gi --image-path "${IMAGE}" --force-bind --insecure
```

**Comment by akalenyu** [comment]
/hold
huh, this breaks the upload tests... not sure why though

**Comment by EduardGomezEscandell** [comment]
> huh, this breaks the upload tests... not sure why though

```
Post "https://https//127.0.0.1:43049/v1beta1/upload": dial tcp: lookup https: no such host
      ^^^^^^^^^^^^
      suspicious
```

**Comment by akalenyu** [comment]
> > huh, this breaks the upload tests... not sure why though
> 
> ```
> Post "https://https//127.0.0.1:43049/v1beta1/upload": dial tcp: lookup https: no such host
>       ~~~~~~~~~~~~~~~
>       |
>       suspicious
> ```

yup that's wrong, note there's no virtctl in this repo so must be the test code that's padding it

**Comment by EduardGomezEscandell** [comment]
Yeah, I fixed it in one place, I'll see if there is more padding elsewhere

**Comment by akalenyu** [comment]
> Yeah, I fixed it in one place, I'll see if there is more padding elsewhere

Ah, I think this will make us fail when testing CDI on OpenShift, since there we will be missing the https:// prefix.
Maybe we do have a bug in the code that grabs the URL from the Route{} object?

**Comment by EduardGomezEscandell** [comment]
The tests grab the URL from the response to a GET for the cdiconfig:
https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/tests/upload_test.go#L979-L986

The UploadProxyURL is set in three different locations in the config controller:

- https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/pkg/controller/config-controller.go#L178
- https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/pkg/controller/config-controller.go#L197
- https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/pkg/controller/config-controller.go#L150

If I understand correctly, the one relevant for these tests is the last one, which seems to take the spec verbatim.

**Comment by akalenyu** [comment]
> The tests grab the URL from the response to a GET for the cdiconfig (this is what I modified in the last commit):
> 
> https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/tests/upload_test.go#L979-L986
> 
> The UploadProxyURL is set in three different locations in the config controller:
> 
> * https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/pkg/controller/config-controller.go#L178
> * https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/pkg/controller/config-controller.go#L197
> * https://github.com/kubevirt/containerized-data-importer/blob/a9e0f52d0a1398a588ef501986efb5a18c0d49a3/pkg/controller/config-controller.go#L150
> 
> If I understand correctly, the one relevant for these tests is the last one, which seems to take the spec verbatim.

For our upstream CI - yeah. For OpenShift it's going to be the first one though, since we're setting up the route.
My suggestion was to prefix https:// in the OpenShift case, but not too sure about that..

Thinking about it some more, for this PR, I think we should just add https:// in the tests if it's missing
Since the tests rely on that

**Comment by alromeros** [comment]
Nice!
/lgtm

**Comment by EduardGomezEscandell** [comment]
Fossa has also repeatedly failed here: https://github.com/kubevirt/containerized-data-importer/pull/3314

Also complaining about docker's license, not sure what is going on.

**Pull request merged**
