### PR TITLE
Switch to minimal fedora 30

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Change our container base image from fedora 29 standard to fedora 30 minimal.
Add a maintainer label to all containers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
Containers are now based on Fedora 30 minimal.
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
Absolutely, good catch, unfortunately doesn't seem like the work I did before about grabbing the mirrors from the STD CI data center is working. I will have to talk with them to see if there is a mirror.

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
I don't think so, since its just for testing and dev environments.

**Comment by mhenriks** [comment]
Okay, but what about upstream @awels?

Also, did you see the unit test failure?

**Comment by awels** [comment]
What do you mean what about upstream? The released containers?

**Comment by mhenriks** [comment]
> What do you mean what about upstream? The released containers?

Yeah, upstream users are using the images we publish to docker hub.  So I wouldn't say these changes only apply to testing and dev environments.

**Comment by awels** [comment]
Okay, I will put in a release note.

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Pull request merged**
