### PR TITLE
Change release user to be cdi-bot

### LINKED ISSUE #769: Release user password might have been compromised in GH breach
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
screeley is the current release user
**What you expected to happen**:
CDI-BOT to be the release-user (also change PW for that user because of GH breach)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- CDI version (use `kubectl get deployments cdi-deployment -o yaml`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Changes the release user to be the CDI-BOT instead of an actual user. This also takes into account that we changed CDI-BOTs password due to GH breach.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #769 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by j-griffith** [comment]
Do you want to open a GH Issue noting the DockerHub breech?  Or at least maybe put a note in the commit message that this addresses that?  There may be folks "grepping" that sort of thing in the future.  Other than that:

/lgtm

**Comment by awels** [comment]
@j-griffith Added some notes about the change due to breach.

**Comment by j-griffith** [comment]
Ok, I realize now that this is actually something we were updating anyway before the breech (ie changing the account), so my question is; is this a new password set in the past 72 hours to deal with the breech issue and possible deactivation of our dockerhub login as well?

**Comment by awels** [comment]
Yes, I generated a new PW for the bot user, and used that to create the api key

**Comment by awels** [comment]
ci test please

**Pull request merged**
