### PR TITLE
[release-v1.58] Add new Prometheus alerts and label existing alerts

### PR DESCRIPTION
**Pull request by arnongilboa**
**What this PR does / why we need it**:

Manual backport of #2998 & #3038

- `CDINoDefaultStorageClass` - not having a default (or virt default) SC is surely not an OpenShift error, as admins may prefer their cluster users to only use explicit SC names. However, in the CDI context when DV is created with default SC but default does not exist, we will fire an error event and the PVC will be Pending for the default SC, so when there are such Pending PVCs we will fire an alert.

- `CDIDefaultStorageClassDegraded` - when the default (or virt default) SC does not support CSI/Snapshot clone (smart clone) or does not have ReadWriteMany access mode (for live migration).

- `CDIStorageProfilesIncomplete` - add storageClass and provisioner labels.

- `CDIDataImportCronOutdated` - add dataImportCron namespace and name labels.

Also:
* Rename the metric `kubevirt_cdi_storageprofile_status` to `kubevirt_cdi_storageprofile_info` since it always reports value 1, where the label values provide the details about the storage class and storage profile.
* Add snapshot manifests for tests and deploy snapshot CRDs in the hpp destructive lane

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes CNV-36773

**Special notes for your reviewer**:

**Release note**:
```release-note
Add Prometheus alerts CDINoDefaultStorageClass and CDIDefaultStorageClassDegraded; add informative labels to existing alerts CDIStorageProfilesIncomplete and CDIDataImportCronOutdated
```

### CODE REVIEW

**Review by akalenyu — COMMENTED** [review]
This is a clean backport right? the only reason it's manual is to aggregate the two PRs?

**Comment by arnongilboa** [comment]
> This is a clean backport right? the only reason it's manual is to aggregate the two PRs?

yep, and fix one line conflict of the CDIMultipleDefaultVirtStorageClasses tests_id :)

**Comment by akalenyu** [comment]
/approve
https://issues.redhat.com/browse/CNV-36773

**Pull request merged**
