### PR TITLE
allow for override of registry and tag in CDI object

### LINKED ISSUE #741: Express ContainerRegistry, ContainerTag, and PullPolicy on the operator's CR
/kind enhancement

Expose ContainerRegistry, ContainerTag, and PullPolicy on the operator's CR and remove them as environment vars.

HCO's [configuration proposal](https://github.com/kubevirt/hyperconverged-cluster-operator/pull/22)

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

See referenced issue.  Basically, add the ability to specify docker repo/tag in CDI object.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #741 

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
attn @lveyde  @rthallisey

**Comment by mhenriks** [comment]
ci test please

**Comment by mhenriks** [comment]
@igoihman I don't think this will affect you much, but please take a look.

**Comment by rthallisey** [comment]
Looks like values are defaulted if nothing gets added to the CR, so LG2M

**Pull request merged**
