### PR TITLE
update kubevirtci

### PR DESCRIPTION
**Pull request by mhenriks**
Signed-off-by: Michael Henriksen <mhenriks@redhat.com>

**What this PR does / why we need it**:

Been awhile since we updated

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by awels — APPROVED** [review]
/lgtm
/approve

**Comment by awels** [comment]
FATAL: either KUBEVIRTCI_TAG or KUBEVIRTCI_GOCLI_CONTAINER must be set
Looks like we need to set something in our CI lanes?

**Comment by maya-r** [comment]
Need to set it whenever running kubectl.sh, which automation/test.sh does

**Pull request merged**
