### PR TITLE
update go to 1.11.5

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Let's use the same version of Go as KubeVirt

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by mhenriks** [comment]
ci test please

**Comment by mhenriks** [comment]
ci test please

**Comment by mhenriks** [comment]
ci test please

**Comment by awels** [comment]
ci test please

**Pull request merged**
