### PR TITLE
Controller Manifest Updates

### PR DESCRIPTION
**Pull request by davidvossel**
These are just some simple changes to the manifest that help the quality of life for other projects consuming the controller manifest.

functionally, nothing is changing here

### CODE REVIEW

**Comment by copejon** [comment]
LGTM

**Comment by jeffvance** [comment]
@davidvossel What is the reason for the `cdi.kubevirt.io` labels vs. this name as annotation prefix? I think the only labels cdi uses are `app=containerized-data-importer`, which the cdi controller adds to the importer pod.

**Comment by davidvossel** [comment]
> What is the reason for the cdi.kubevirt.io labels vs. this string used as an annotation prefix? I think the only labels cdi uses are app=containerized-data-importer, which the cdi controller adds to the importer pod.

With the cdi.kubevirt.io label we have a consistent way to recognize anything involved CDI's installed components. It helps with deprovisioning. I can run something like this.

```
kubectl delete deployment -l 'cdi.kubevirt.io'
kubectl delete serviceaccounts -l 'cdi.kubevirt.io'
kubectl delete clusterroles -l 'cdi.kubevirt.io'
kubectl delete clusterrolebinding -l 'cdi.kubevirt.io'
kubectl delete customresourcedefinitions -l 'cdi.kubevirt.io'
```

And it will remove cdi related artifacts even if the names of the deployment, serviceaccount, etc... change later on. We do the same thing in kubevirt.  All the kubevirt components have a kubevirt.io label. We use that label to deprovision kubevirt.

**Comment by jeffvance** [comment]
@davidvossel 
> cdi.kubevirt.io label we have a consistent way to recognize anything involved CDI's installed components

So, does it make sense to _also_ have the importer `app=containerized-data-importer`?

**Comment by davidvossel** [comment]
> So, does it make sense to also have the importer app=containerized-data-importer label?

yeah, cdi.kubevirt.io should probably replace the app label

**Comment by copejon** [comment]
lgtm, just rebase and we'll merge

**Pull request merged**
