### PR TITLE
apidocs: remove gradle dep (gen-swagger-docs.sh)

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Use builder provided substitutes to gradle in `gen-swagger-docs.sh`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
apidocs: remove gradle dep (gen-swagger-docs.sh)
```

### CODE REVIEW

**Comment by mhenriks** [comment]
/hold

need #3389

**Comment by akalenyu** [comment]
/test pull-containerized-data-importer-e2e-hpp-latest
should work now with https://github.com/kubevirt/containerized-data-importer/pull/3378 in

**Pull request merged**
