### PR TITLE
Add Ceph DV GC lane automation script

### PR DESCRIPTION
**Pull request by arnongilboa**
Signed-off-by: Arnon Gilboa <agilboa@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by akalenyu** [comment]
Are we fine with the GC lane being a ceph one? just asking because HPP might be cheaper, I could be missing a downside though

**Comment by akalenyu** [comment]
> > Are we fine with the GC lane being a ceph one? just asking because HPP might be cheaper, I could be missing a downside though
> > @mhenriks commented that since hpp does not support smart clone it would be better to test ttl on/off with rook ceph

gotcha
/lgtm

**Comment by awels** [comment]
Note the lane is not automatically run nor required at this point, which is good because we are still testing it. But please run it a few times manually so we can see it is working well before enabling it full time.

**Comment by arnongilboa** [comment]
> Note the lane is not automatically run nor required at this point, which is good because we are still testing it. But please run it a few times manually so we can see it is working well before enabling it full time.

sure, that's the idea

**Pull request merged**
