### PR TITLE
Update kubevirtci images to refresh certificates.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
Update kubevirtci image hashes to latest, so we have fresh certificates, current ones expired. Also local storage is now part of the image.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
ci test please

**Comment by aglitke** [comment]
Is there a command documented in our repo how to update our copy of the cluster-up code from latest?  Ie.  is that part automated?

**Comment by awels** [comment]
its in the kubevirtci repo, basically update the git hash in  hack/update-codegen.sh and run make generate, that will grab the latest and update.

**Comment by awels** [comment]
ci test please

**Pull request merged**
