### PR TITLE
Minor fix to a manifest example, import-kubevirt-block-datavolume

### PR DESCRIPTION
**Pull request by isueyoon**
Signed-off-by: isueyoon <sueyoon@protonmail.com>

**What this PR does / why we need it**:
It's a very tiny fix to an example yaml file, import-kubevirt-block-datavolume.yaml. Moved storageClassName key, value under the pvc.

I copy and pasted this example to create a data volume, and noticed why it didn't work.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

It's a same request as #1173 which I closed few days ago by mistake. 

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Thanks for the PR, looks good.

**Comment by maya-r** [comment]
/test pull-containerized-data-importer-e2e-k8s-1.16.2-upg
(sorry)

**Pull request merged**
