### PR TITLE
Correct typo in deprecation note for ObjectTransfer

### PR DESCRIPTION
**Pull request by akalenyu**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by ShellyKa13 — APPROVED** [review]
/lgtm

**Comment by akalenyu** [comment]
/override pull-containerized-data-importer-e2e-nfs
guess similar to https://github.com/kubevirt/kubevirt/pull/13443

**Pull request merged**
