### PR TITLE
Correct the cloneStrategy on StorageProfile

### PR DESCRIPTION
**Pull request by brybacki**
**What this PR does / why we need it**:

Moves the cloneStrategy up one level from claimPropertySet to StorageProfile.spec and StorageProfile.status.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

https://bugzilla.redhat.com/show_bug.cgi?id=2006418

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by brybacki** [comment]
This is strange:
`The Service "cdi-uploadproxy-nodeport" is invalid: spec.ports[0].nodePort: Invalid value: 31001: provided port is already allocated`

/test pull-containerized-data-importer-e2e-k8s-1.20-upg

**Review by awels — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
