### PR TITLE
Unify untar code.

### PR DESCRIPTION
**Pull request by awels**
Signed-off-by: Alexander Wels <awels@redhat.com>

**What this PR does / why we need it**:
This PR unifies the tar code to be shared across different areas.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
I tried, but you guys are passing the source URL directly into tar, which I am guessing then uses the shell to actually get the stream of data. The other two tars take a stream. I haven't figured out yet, how to get a stream in GO from an arbitrary (docker://xxx in this case) URI.

**Comment by rollandf** [comment]
OK, thanks!
:+1:

**Comment by awels** [comment]
Sweet, I will look at it.

**Comment by awels** [comment]
I think #553 does everything this patch does, closing.

**Pull request closed without merging**
