### PR TITLE
Flaky certrotation tests

### PR DESCRIPTION
**Pull request by mhenriks**
**What this PR does / why we need it**:

Synchronization between fake client and lister could cause flakes

Test assuming creates would be seen immedietly but updates would not

Solution is to forget about validating anything library-go package may do

It's not our code anyway!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by akalenyu — COMMENTED** [review]
Looks good. Are we maybe interested in something like https://github.com/kubevirt/kubevirt/blob/392a8c5b1af36eff340d83d9eec123bf8438bd00/pkg/storage/export/export/export_test.go#L195 too?
I've seen this also flake with `secrets "cdi-uploadserver-client-cert" already exists`:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3336/pull-cdi-goveralls/1809334945819136000

**Comment by mhenriks** [comment]
> Looks good. Are we maybe interested in something like https://github.com/kubevirt/kubevirt/blob/392a8c5b1af36eff340d83d9eec123bf8438bd00/pkg/storage/export/export/export_test.go#L195 too?

What's the benefit?  Fake informers are indirectly still being made under the covers

> I've seen this also flake with secrets "cdi-uploadserver-client-cert" already exists:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/3336/pull-cdi-goveralls/1809334945819136000

yeah we can handle that

**Review by akalenyu — COMMENTED** [review]
/approve

**Comment by akalenyu** [comment]
> What's the benefit? Fake informers are indirectly still being made under the covers

I thought the fake source has some special impl. that would make this more unit-test appropriate, but I guess that's not the case. I don't recall us having to deal with this kind of problem in kubevirt unit tests?

**Comment by mhenriks** [comment]
> > What's the benefit? Fake informers are indirectly still being made under the covers
> 
> I thought the fake source has some special impl. that would make this more unit-test appropriate, but I guess that's not the case. I don't recall us having to deal with this kind of problem in kubevirt unit tests?

I think it is kind of unusual (in a unit test) for an application to get a cached resource, update it, then read it from the cache AGAIN and expect to see the update, which is what is happening here.  Usually just read from the cache once

**Pull request merged**
