### PR TITLE
add vendor support

### PR DESCRIPTION
**Pull request by shiywang**
Fixes: https://github.com/kubevirt/containerized-data-importer/issues/52
I think the reason I can run test locally is because previously my GOPATH  already include those `onsi` repo. 

@jeffvance PTAL, thanks

### CODE REVIEW

**Comment by jeffvance** [comment]
@copejon  ptal. It looks like @shiywang did a glide update like I did last week resulting in 400+ new/changed files. 
@shiywang I ended up just using `go get github.com/onsi/(ginkgo||gomega)`

**Comment by shiywang** [comment]
>@copejon ptal. It looks like @shiywang did a glide update like I did last week resulting in 400+ new/changed files.

Yeah, I did `glide update`, not the right command ?

>@shiywang I ended up just using go get github.com/onsi/(ginkgo||gomega)

I did that like one year ago, so that's the reason I can pass on my local

**Comment by copejon** [comment]
Not sure how much it will cut down on size but to reduce redundant nested dependencies ( `vendor/a/vendor/b` and `vendor/c/vendor/b`) use `glide up -v`.  This will extract redundant deps up to the top `vendor/` level for shared access between other dependencies:
`vendor/b`
`vendor/a/vendor/b->vendor/b`
`vendor/c/vendor/b->vendor/b`

Aside from that, LGTM

**Comment by shiywang** [comment]
@copejon hi, the command I used was `glide update -v`, and I did that again, and nothing changed, when you said redundant do you mean this?
`~/GOPATH/src/github.com/kubevirt/containerized-data-importer/vendor/github.com/onsi`
`~/GOPATH/src/github.com/onsi/`

I'm still a little confuse how to reduce this nested dependencies ?

**Comment by copejon** [comment]
If it didn't reduce the file count, that's okay.  I'd say it's clear to merge then.

Regarding `-v`: I mean _vendored_ deps can also have their own `vendor/` directories:

`~/GOPATH/src/github.com/myProject/*vendor*/myDep/**vendor**/someDep`

Often times, these vendored deps can have the same nested, vendored dependencies:

`~/GOPATH/src/github.com/myProject/*vendor*/myFirstDep/**vendor**/someNestedDep`
`~/GOPATH/src/github.com/myProject/*vendor*/mySecondDep/**vendor**/someNestedDep`

See here 2 vendored deps have the same nested dep: `/someNestedDep`.

Using `-v` "flattens" the common dependencies and remove the nested `/vendor/` directory:

`~/GOPATH/src/github.com/myProject/vendor/myFirstDep/`
`~/GOPATH/src/github.com/myProject/vendor/mySecondDep/`
`~/GOPATH/src/github.com/myProject/vendor/someNestedDep`

And the golang compiler can figure out import paths from `myFirstDep` and `mySecondDep` to `someNestedDep`

I hope I explained that properly!

LGTM!

**Comment by shiywang** [comment]
@copejon thank you for the detailed explain :+1:

**Pull request merged**
